import {test,expect,type Page} from '@playwright/test';
import {mkdirSync,writeFileSync} from 'node:fs';
import {syncMapGeometry} from '../src/data/world';
import {CAMP_BOSSES,BOSS_RULES} from '../src/data/maps/windbell/campBosses';
import {ENCOUNTERS} from '../src/data/maps/windbell/encounters';
import {VILLAGE_ANCHORS} from '../src/data/maps/windbell/layout';
import {motionBlocked,clearMotionLine} from '../src/game/systems/obstacles';
import {move} from './map-navigation';
import {fight} from './field-combat';
const read=(p:Page)=>p.evaluate(()=>(window as any).__farwind());
const root='docs/camp-bosses/evidence/world-retreat-raid';
async function waitMinute(page:Page,minute:number){
 const end=Date.now()+1200000;let logged=0;while(Date.now()<end){const s=await read(page);if(Date.now()-logged>30000){logged=Date.now();writeFileSync(root+'/clock-progress.json',JSON.stringify({说明:'从真实运行快照读取自然世界时间，不修改时钟。',目标分钟:minute,当前分钟:s.state.time,玩家生命:s.state.player.hp,当前界面:s.mode,首领状态:s.state.encounters.groups['south-spore-camp'].boss.stage,夜间计划:s.state.night.plan},null,2));}if(s.state.time>=minute)return;if(s.mode==='dialog')await page.getByRole('button',{name:'继续 · E',exact:true}).click();else if(s.mode)throw Error('常规昼夜推进被界面中断：'+s.mode);await page.waitForTimeout(1000);}throw Error('等待自然世界时间超时。');
}
async function orient(page:Page,dx:number,dy:number,ms=80){const key=Math.abs(dx)>Math.abs(dy)?dx<0?'a':'d':dy<0?'w':'s';await page.keyboard.down(key);await page.waitForTimeout(ms);await page.keyboard.up(key);}
async function south(page:Page){for(const [x,y] of [[900,1900],[1050,2040],[1000,2450],[1250,2820]])await move(page,x,y);}
async function village(page:Page){await page.keyboard.down('Space');try{for(const [x,y] of [[1000,2450],[1050,2040],[900,1900],[900,1750],[900,1000],[670,720]])await move(page,x,y);}finally{await page.keyboard.up('Space');}}
test('world-retreat-raid',async({page})=>{
 test.setTimeout(2100000);syncMapGeometry(false);mkdirSync(root,{recursive:true});const errors:string[]=[],report:any={说明:'关闭测试授予的正式构建，从新游戏出发。等待自然昼夜并通过旅馆住宿到次日，不导入、加速或修改游戏状态。关闭辅助提示，真实撤战守村，再回据点重新入场。',节点:[],错误:errors,结果:'进行中'};page.on('pageerror',e=>errors.push(e.message));
 const save=()=>writeFileSync(root+'/world.json',JSON.stringify(report,null,2));
 const shot=async(name:string,file:string)=>{const s=await read(page);report.节点.push({名称:name,世界分钟:s.state.time,模拟毫秒:s.skillGrowth.sim,玩家:s.state.player,据点:s.state.encounters.groups['south-spore-camp'],危险区:s.bossHazards,夜袭:s.state.night,防御:s.defense});save();await page.screenshot({path:root+'/'+file+'.png'});};
 try{
  await page.goto('/');await page.getByRole('button',{name:'启程 · 新游戏',exact:true}).click();await page.waitForFunction(()=>(window as any).__farwind?.().mode==='');
  await move(page,560,810);await page.keyboard.press('e');await page.getByRole('button',{name:'领取委托与启程补给',exact:true}).click();await expect(page.locator('#commission-feedback')).toContainText('委托已领取');await page.getByRole('button',{name:'合上委托簿 Esc',exact:true}).click();
  await move(page,VILLAGE_ANCHORS.general.x,VILLAGE_ANCHORS.general.y+65);await page.keyboard.press('e');await page.getByLabel('物品',{exact:true}).selectOption('potion');await page.getByLabel('数量',{exact:true}).fill('2');await page.locator('#shop-review').click();await page.locator('#shop-confirm').click();await expect(page.locator('#shop-feedback')).toContainText('已完成');await page.keyboard.press('Escape');
  await move(page,VILLAGE_ANCHORS.smith.x,VILLAGE_ANCHORS.smith.y+65);await page.keyboard.press('e');await page.getByLabel('物品',{exact:true}).selectOption('ironSword');await page.locator('#shop-review').click();await page.locator('#shop-confirm').click();await expect(page.locator('#shop-feedback')).toContainText('已完成');await page.keyboard.press('Escape');
  await page.keyboard.press('Tab');await page.locator('.slot').filter({hasText:'铁剑'}).click();await page.locator('#equip').click();await page.waitForFunction(()=>(window as any).__farwind().state.equipment.weapon==='ironSword');await page.keyboard.press('Escape');
  await move(page,850,790);await page.getByRole('button',{name:'迎风架剑练习',exact:true}).click();await page.locator('#parry-indicators').uncheck();await page.getByRole('button',{name:'结束弹反练习',exact:true}).click();expect((await read(page)).state.skills.swordWindStage).toBe(0);
  await south(page);const camp=ENCOUNTERS.find(d=>d.id==='south-spore-camp')!;await fight(page,camp.members.filter(m=>!m.boss).map(m=>m.id));await page.waitForFunction(()=>(window as any).__farwind().enemies.some((e:any)=>e.id==='boss-spore-heart'&&e.hp>0));
  await page.setViewportSize({width:400,height:720});await page.waitForTimeout(150);const layout=await page.locator('#camp-boss-status').evaluate(el=>{const r=el.getBoundingClientRect();return {左:r.left,右:r.right,宽:r.width,布局:getComputedStyle(el).position,子元素:[...el.querySelectorAll('*')].map(e=>{const r=e.getBoundingClientRect();return {左:r.left,右:r.right,宽:r.width};})};});expect(layout.布局).toBe('static');expect(layout.左).toBeGreaterThanOrEqual(0);expect(layout.右).toBeLessThanOrEqual(400);for(const r of layout.子元素.filter(r=>r.宽>0)){expect(r.左).toBeGreaterThanOrEqual(0);expect(r.右).toBeLessThanOrEqual(400);}report.窄屏=layout;await shot('四百像素宽首领信息自然换行','narrow-hud');await page.setViewportSize({width:1280,height:720});
  await page.waitForFunction(()=>(window as any).__farwind().bossHazards.some((h:any)=>h.kind==='circle'),undefined,{timeout:20000});await shot('关闭来招辅助后，关键根刺地面标记仍可见','ground-without-assistance');
  const first=(await read(page)).state.encounters.groups[camp.id].boss.attempt;await village(page);await page.waitForTimeout(BOSS_RULES.retreat+100);const reset=(await read(page)).state.encounters.groups[camp.id];expect(reset.boss.attempt).toBe(first+1);expect(reset.members.at(-1).hp).toBe(CAMP_BOSSES['spore-heart'].hp);expect(reset.members.slice(0,-1).every((m:any)=>m.defeated)).toBe(true);expect((await read(page)).bossHazards).toHaveLength(0);await shot('真正离开战斗范围八秒，首领满血而杂兵不复活','retreat-reset');
  await move(page,1685,1680);console.log('世界样本：等待第一夜，随后正常住宿。');await waitMinute(page,1141);await page.keyboard.press('e');await page.locator('[data-flow="sleep"]').click();await page.locator('#shop-review').click();await page.locator('#shop-confirm').click();await expect(page.locator('#shop-feedback')).toContainText('已完成');await page.locator('#close').click();await shot('正常旅馆住宿至第二日黎明','second-day');
  console.log('世界样本：等待第二夜的自然来袭计划。');await waitMinute(page,2461);const night=(await read(page)).state.night.plan;expect(night.night).toBe(2);expect(night.outcome).toBe('pending');await waitMinute(page,night.at-40);expect((await read(page)).state.player.hp).toBe(100);expect((await read(page)).state.encounters.groups[camp.id].boss.attempt).toBe(first+1);await shot('在村内安全等待至自然来袭前，未触发首领或额外死亡','before-raid-entry');await page.keyboard.down('Space');try{await south(page);}finally{await page.keyboard.up('Space');}
  await page.waitForFunction(()=>(window as any).__farwind().state.encounters.groups['south-spore-camp'].boss.stage==='battle');expect((await read(page)).state.encounters.groups[camp.id].boss.attempt).toBe(first+1);const waiting=Date.now(),sim=(await read(page)).skillGrowth.sim;
  while(Date.now()-waiting<90000){const s=await read(page);if(s.state.defense.raid)break;const p=s.state.player,e=s.enemies.find((e:any)=>e.id==='boss-spore-heart'&&e.hp>0);if(!e)throw Error('夜袭前首领挑战已重置。');if(p.hp<55)await page.keyboard.press('1');const choices=[{x:camp.x+220,y:camp.y+140},{x:camp.x-220,y:camp.y+140},{x:camp.x,y:camp.y-220}].filter(q=>!motionBlocked(q.x,q.y)&&clearMotionLine(p,q));const goal=choices.sort((a,b)=>Math.hypot(b.x-e.x,b.y-e.y)-Math.hypot(a.x-e.x,a.y-e.y))[0];if(goal)await orient(page,goal.x-p.x,goal.y-p.y,150);else await page.waitForTimeout(100);}
  const simultaneous=await read(page),raid=simultaneous.state.defense.raid;expect(raid).not.toBe(null);expect(simultaneous.skillGrowth.sim).toBeGreaterThan(sim);expect(simultaneous.state.encounters.groups[camp.id].boss.stage).toBe('battle');await shot('首领战继续推进时正式夜袭启动','boss-and-raid');const raidId=raid.id,sequence=raid.sequence;
  await village(page);await page.waitForTimeout(BOSS_RULES.retreat+100);await shot('撤战回村，防线继续处理原序号来袭','defend-village');const home=await read(page);expect(home.state.encounters.groups[camp.id].boss.attempt).toBe(first+2);if(home.state.defense.raid)expect(home.state.defense.raid.id).toBe(raidId);else expect(home.state.defense.completedSequence).toBe(sequence);
  const deadline=Date.now()+120000;while(Date.now()<deadline){const s=await read(page);if(s.state.defense.completedSequence>=sequence)break;const e=s.defense.enemies.filter((e:any)=>e.hp>0).sort((a:any,b:any)=>Math.hypot(a.x-s.state.player.x,a.y-s.state.player.y)-Math.hypot(b.x-s.state.player.x,b.y-s.state.player.y))[0];if(s.state.player.hp<55)await page.keyboard.press('1');if(e){await orient(page,e.x-s.state.player.x,e.y-s.state.player.y,Math.hypot(e.x-s.state.player.x,e.y-s.state.player.y)>95?100:20);await page.keyboard.press('j');}await page.waitForTimeout(160);}
  expect((await read(page)).state.defense.completedSequence).toBe(sequence);await shot('原夜袭自然结算，没有被撤战或首领重置取消','raid-complete');await south(page);await page.waitForFunction(()=>(window as any).__farwind().state.encounters.groups['south-spore-camp'].boss.stage==='battle');const again=(await read(page)).state.encounters.groups[camp.id];expect(again.boss.attempt).toBe(first+2);expect(again.members.at(-1).hp).toBe(CAMP_BOSSES['spore-heart'].hp);expect(again.members.slice(0,-1).every((m:any)=>m.defeated)).toBe(true);await shot('守村后重新挑战同一据点，首领满血且杂兵保持清除','rechallenge');expect(errors).toEqual([]);report.结果='通过';
 }catch(error){report.结果='未通过';report.原因=(error as Error).message;report.失败时状态=await read(page);await page.screenshot({path:root+'/failure.png'});throw error;}finally{save();const video=page.video();await page.close();if(video)await video.saveAs(root+'/gameplay.webm');}
});
