import {test,expect,type Page} from "@playwright/test";
import {initialState,type State} from "../src/game/systems/state";
import {prepareRaid} from "../src/game/systems/defense";
const read=(p:Page)=>p.evaluate(()=>(window as any).__farwind());
async function fixture(page:Page,s:State){await page.goto("/?dayNightDebug=1&npcDebug=1&defenseDebug=1");page.once("dialog",d=>d.accept());const file=page.waitForEvent("filechooser");await page.getByRole("button",{name:"导入存档",exact:true}).click();await(await file).setFiles({name:"production-night.json",mimeType:"application/json",buffer:Buffer.from(JSON.stringify(s))});await expect(page.locator("#hud")).toBeVisible();await page.waitForTimeout(350);}
async function sleep(page:Page){await page.keyboard.press("e");await page.locator('[data-flow="sleep"]').click();await page.locator("#shop-review").click();await page.locator("#shop-confirm").click();}
test("正式构建住宿、继续、可见度和调试隔离",async({page})=>{
 const errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));const s=initialState();s.time=1260;s.player.x=1685;s.player.y=1680;await fixture(page,s);
 expect((await read(page)).dayNight).toBeUndefined();await expect(page.locator("#day-night-debug")).toHaveCount(0);await expect(page.getByRole("button",{name:"NPC 调试",exact:true})).toHaveCount(0);await sleep(page);await expect(page.locator("#shop-feedback")).toContainText("已完成");const n=(await read(page)).state;expect([n.coins,n.time,n.night.plan.outcome]).toEqual([108,1800,"skipped"]);await page.locator("#close").click();await expect(page.locator("#clock")).toContainText("黎明");await page.waitForTimeout(350);await page.screenshot({path:"docs/day-night/evidence/m5-production-dawn.png"});
 await page.keyboard.press("Escape");await page.getByRole("button",{name:"设置",exact:true}).click();await page.locator("#night-visibility").press("Home");await page.getByRole("button",{name:"返回",exact:true}).click();await page.getByRole("button",{name:"保存并返回标题"}).click();const saved=(await read(page)).state;await page.reload();await page.getByRole("button",{name:"继续旅途",exact:true}).click();const restored=(await read(page)).state;expect([restored.coins,restored.night.plan.outcome]).toEqual([108,"skipped"]);expect(restored.defense.protectionMs+(restored.time-saved.time)/1.5*1000).toBeCloseTo(saved.defense.protectionMs,3);expect(restored.time).toBeGreaterThanOrEqual(1800);expect(errors).toEqual([]);
});
test("正式构建跨午夜与未结束来袭拒绝住宿",async({page})=>{
 const s=initialState();s.time=1439.85;await fixture(page,s);await expect.poll(async()=>(await read(page)).state.time).toBeGreaterThan(1440);await expect(page.locator("#clock")).toContainText("第2日 00:");expect((await read(page)).state.defense.sequence).toBe(0);await page.keyboard.press("Escape");await page.getByRole("button",{name:"保存旅途",exact:true}).click();await page.reload();await page.getByRole("button",{name:"继续旅途",exact:true}).click();await expect(page.locator("#clock")).toContainText("第2日 00:");
 const n=initialState();n.time=1260;n.player.x=1685;n.player.y=1680;n.defense=prepareRaid(n.defense,{x:670,y:720},"east-gate",2,true);await fixture(page,n);await sleep(page);await expect(page.locator("#shop-feedback")).toContainText("未完成");expect((await read(page)).state.coins).toBe(120);await page.waitForTimeout(350);await page.screenshot({path:"docs/day-night/evidence/m4-active-raid-failed.png"});await page.locator("#close").click();await expect(page.locator("#modal")).toBeHidden();
});
