import {test,expect,type Page} from '@playwright/test';
import {mkdirSync,writeFileSync} from 'node:fs';
import {move} from './map-navigation';
import {fight} from './field-combat';
import {syncMapGeometry} from '../src/data/world';
import {RAID_GATES} from '../src/data/defense';
import {demonMalice} from '../src/game/systems/demonKingState';
const root='docs/demon-king-design/evidence';
const read=(p:Page)=>p.evaluate(()=>(window as any).__farwind());
test('DEMON-KING-01',async({page})=>{
 mkdirSync(root,{recursive:true});syncMapGeometry(false);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 const report:any={说明:'隔离正式构建，以实际键鼠完成新游戏、清剿、住宿、保存与重新加载。夜间派遣等待正常游玩时钟；没有设置坐标、生命、清剿、恶意、时间或冷却。',节点:[],错误:errors};
 const snap=async(name:string,file:string)=>{const s=await read(page);report.节点.push({名称:name,状态:s.state,驻防:s.defense,荒野:s.wilderness});writeFileSync(`${root}/browser.json`,JSON.stringify({...report,结果:'进行中'},null,2));await page.screenshot({path:`${root}/${file}.png`});};
 await page.goto('/');await page.getByRole('button',{name:'启程 · 新游戏',exact:true}).click();await page.waitForFunction(()=>(window as any).__farwind?.().mode==='');
 expect(demonMalice((await read(page)).state.encounters)).toBe(0);
 await move(page,560,810);await page.waitForFunction(()=>(window as any).__farwind().target==='community-ledger');await page.keyboard.press('e');
 await page.getByRole('button',{name:'委托 · 南路补给',exact:true}).click();await page.getByRole('button',{name:'领取委托与启程补给',exact:true}).click();await page.keyboard.press('Escape');
 await move(page,900,1950);await move(page,1050,2040);await fight(page,['wild-reed-slime']);
 await move(page,1000,2450);await move(page,790,2480);await fight(page,['wild-herb-spore','wild-herb-slime']);
 await move(page,740,2530);await page.waitForFunction(()=>(window as any).__farwind().target==='wild-resource-2');await page.keyboard.press('e');
 await move(page,1250,2820);await fight(page,['wild-camp-spore','wild-camp-slime-a','wild-camp-slime-b']);
 await page.waitForFunction(()=>(window as any).__farwind().state.encounters.groups['south-spore-camp'].cleared);
 expect(demonMalice((await read(page)).state.encounters)).toBe(1);
 await page.waitForFunction(()=>document.querySelector('#dialog-title')?.textContent==='？？？',{},{timeout:20000});
 await snap('首次清剿后未知的黑焰警告','first-appearance');await expect(page.locator('#dialog-text')).toContainText('这片土地，也有它们活下去的位置');
 await page.getByRole('button',{name:'继续 · E',exact:true}).click();await page.waitForFunction(()=>(window as any).__farwind().state.demonKing.introduced);
 await page.keyboard.press('q');await expect(page.locator('#modal')).toContainText('原编队增加 5 只');await snap('恶意一点的旅途手记','malice-journal');await page.keyboard.press('Escape');
 // 战斗落点贴近湿地岸线，先用真实左移离岸，避免测试寻路把落点取整到水边。
 await page.keyboard.down('a');await page.waitForTimeout(300);await page.keyboard.up('a');
 await move(page,1000,2450);await move(page,900,1900);await move(page,560,810);await page.keyboard.press('e');
 await page.getByRole('button',{name:'委托 · 南路补给',exact:true}).click();await page.getByRole('button',{name:'交付药草并领取奖励',exact:true}).click();await page.keyboard.press('Escape');
 await page.keyboard.press('Escape');await page.getByRole('button',{name:'保存旅途',exact:true}).click();await expect(page.locator('#toast')).toContainText('已保存');
 await page.reload();await page.getByRole('button',{name:'继续旅途',exact:true}).click();await page.waitForFunction(()=>(window as any).__farwind().mode==='');
 const restored=(await read(page)).state;expect(restored.schema_version).toBe(14);expect(restored.demonKing.introduced).toBe(true);expect(demonMalice(restored.encounters)).toBe(1);expect(restored.fieldQuests['south-supply']).toBe('complete');
 await expect(page.locator('#demon-king-summary')).toContainText('恶意 1');await expect(page.locator('#demon-king-summary')).toHaveAttribute('title',/？？？ · 恶意 1/);await snap('读档保留恶意和初见消费','reloaded');
 await move(page,1685,1680);await page.waitForFunction(()=>(window as any).__farwind().state.time%1440>=1140,{},{timeout:600000});
 await page.waitForFunction(()=>(window as any).__farwind().target==='service-inn');await page.keyboard.press('e');
 await page.locator('[data-flow="sleep"]').click();await page.locator('#shop-review').click();await page.locator('#shop-confirm').click();await expect(page.locator('#shop-feedback')).toContainText('已完成');await page.locator('#close').click();
 expect((await read(page)).state.night.plan?.outcome).toBe('skipped');await snap('正常住宿跳过首夜，恶意仍为一点','first-night-slept');
 await move(page,1050,720);await snap('等待第二夜，保护与冷却按实际游玩推进','awaiting-night');
 await page.waitForFunction(()=>(window as any).__farwind().state.defense.raid?.phase==='warning',{},{timeout:720000});
 const warning=(await read(page)).state.defense.raid;expect(warning.order).toEqual({source:'demon-king',malice:1,profileVersion:1});expect(warning.members).toHaveLength(6);await snap('自然第二夜发布已保存的六只王令预警','warning');
 await page.waitForFunction(()=>{const d=(window as any).__farwind();return d.state.defense.raid&&d.state.defense.raid.phase!=='warning'&&d.defense.enemies.length===6;});await snap('六只魔物正式生成，零精英阶位','six-spawned');
 const gate=RAID_GATES.find(g=>g.id===warning.gateId)!;await move(page,gate.inside.x,gate.inside.y);await snap('沿实际道路观察村门战斗','village-fight');
 await page.waitForFunction(()=>(window as any).__farwind().state.defense.raid===null,{},{timeout:150000});
 const final=(await read(page)).state;expect(final.defense.completedSequence).toBe(1);expect(demonMalice(final.encounters)).toBe(1);expect(final.defense.guards.filter((g:any)=>g.id.startsWith(gate.id.split('-')[0])&&!g.dead).length).toBe(3);expect(errors).toEqual([]);
 await snap('一次派遣完整结算，清剿进度未重复计数','raid-ended');report.结果='通过';writeFileSync(`${root}/browser.json`,JSON.stringify(report,null,2));
});
