import {fight} from "./field-combat";
import {ENCOUNTERS,encounterUnit} from "../src/data/maps/windbell/encounters";
import {test,expect,type Page} from "@playwright/test";
import {mkdirSync,writeFileSync} from "node:fs";
import {move} from "./map-navigation";
import {syncMapGeometry} from "../src/data/world";
const root=process.env.FARWIND_MAP_EVIDENCE_ROOT??"docs/first-map/evidence-m3";
const read=(page:Page)=>page.evaluate(()=>(window as any).__farwind());
test("FIRST-MAP-04",async({page})=>{
 test.setTimeout(600000);mkdirSync(root,{recursive:true});syncMapGeometry(false);const errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));
 await page.goto("/");await page.getByRole("button",{name:"启程 · 新游戏",exact:true}).click();await page.waitForFunction(()=>(window as any).__farwind?.().mode==="");
 const report:any={说明:"正式构建新游戏，主角独自沿南路领取、采集、战斗、清剿、交付与保存重开；未设置坐标、生命或任务结果。",节点:[],错误:errors};
 const snap=async(name:string,file:string)=>{const s=await read(page);report.节点.push({名称:name,状态:s.state,敌人:s.enemies,荒野:s.wilderness});writeFileSync(`${root}/field-loop.json`,JSON.stringify({...report,结果:"进行中"},null,2));await page.screenshot({path:`${root}/${file}.png`});};
 await move(page,560,810);await page.waitForFunction(()=>(window as any).__farwind().target==="community-ledger");await page.keyboard.press("e");await page.getByRole("button",{name:"委托 · 南路补给",exact:true}).click();await page.getByRole("button",{name:"领取委托与启程补给",exact:true}).click();await page.waitForFunction(()=>(window as any).__farwind().state.fieldQuests["south-supply"]==="active");await page.keyboard.press("Escape");
 await snap("从公共委托簿领取启程补给","accepted");
 expect((await read(page)).wilderness.south.raidBudget).toBe(3);
 await move(page,900,1950);await move(page,1050,2040);await page.waitForFunction(()=>(window as any).__farwind().enemies.some((e:any)=>e.id==="wild-reed-slime"));
 await fight(page,["wild-reed-slime"]);await snap("渡口近战遭遇","reed-cleared");
 await move(page,1000,2450);await move(page,790,2480);await fight(page,["wild-herb-spore","wild-herb-slime"]);
 await move(page,740,2530);await page.waitForFunction(()=>(window as any).__farwind().target==="wild-resource-2");await page.keyboard.press("e");await snap("清理洼地并采集药草","herbs");
 await move(page,1250,2820);await fight(page,["wild-camp-spore","wild-camp-slime-a","wild-camp-slime-b"]);
 await page.waitForFunction(()=>(window as any).__farwind().state.encounters.groups["south-spore-camp"].cleared,undefined,{timeout:10000});await snap("孢根巢地清剿后的实际画面","camp-cleared");
 expect((await read(page)).wilderness.south).toMatchObject({cleared:true,raidBudget:0,renewablePatrols:0});
 expect((await read(page)).state.encounters.groups["south-spore-camp"].members.every((u:any)=>u.participated)).toBe(true);
 await move(page,1000,2450);await move(page,900,1900);await move(page,560,810);await page.waitForFunction(()=>(window as any).__farwind().target==="community-ledger");
 const before=(await read(page)).state;await page.keyboard.press("e");await page.getByRole("button",{name:"委托 · 南路补给",exact:true}).click();await page.getByRole("button",{name:"交付药草并领取奖励",exact:true}).click();await page.waitForFunction(()=>(window as any).__farwind().state.fieldQuests["south-supply"]==="complete");await page.keyboard.press("Escape");await snap("返村完成补给委托","returned");
 const completed=(await read(page)).state;expect(completed.coins).toBe(before.coins+24);expect(completed.killed.every((id:string)=>!id.startsWith("wild-"))).toBe(true);
 await page.keyboard.press("Escape");await page.getByRole("button",{name:"保存旅途",exact:true}).click();await expect(page.locator("#toast")).toContainText("已保存");await page.reload();await page.getByRole("button",{name:"继续旅途",exact:true}).click();await page.waitForFunction(()=>(window as any).__farwind().mode==="");
 const restored=(await read(page)).state;expect(restored.fieldQuests).toEqual(completed.fieldQuests);expect(restored.coins).toBe(completed.coins);expect(restored.encounters.groups["south-spore-camp"].cleared).toBe(true);expect(restored.xiaobao.task).toBe("free");expect(errors).toEqual([]);
 await snap("重开后清剿与奖励保持","reloaded");report.结果="通过";writeFileSync(`${root}/field-loop.json`,JSON.stringify(report,null,2));
});
