import {test,expect} from '@playwright/test';
import {mkdir,writeFile} from 'node:fs/promises';
import sharp from 'sharp';
import {initialState} from '../src/game/systems/state';
test('V3-PRODUCTION-real-input',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.goto('/?feedback=A');const s=initialState();s.quest=3;Object.assign(s.player,{x:850,y:720});const chooser=page.waitForEvent('filechooser');await page.getByRole('button',{name:'导入存档',exact:true}).click();await(await chooser).setFiles({name:'production-fixture.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(s))});await page.waitForFunction(()=>(window as any).__farwind().mode==='');await page.keyboard.press('k');await expect(page.locator('.meter.stamina')).toContainText('88 / 100');await page.waitForTimeout(450);await page.mouse.click(650,390,{button:'right'});await expect.poll(async()=>page.evaluate(()=>(window as any).__farwind().state.player.stamina)).toBeLessThan(85);await page.waitForTimeout(450);await page.keyboard.press('w');await page.waitForTimeout(40);await page.getByRole('button',{name:'迎风架剑练习',exact:true}).click();await page.getByRole('button',{name:'慢速教学 · 900毫秒',exact:true}).click();
 let received=false;for(let i=0;i<180;i++){const png=await page.screenshot({clip:{x:580,y:330,width:130,height:160}}),{data}=await sharp(png).ensureAlpha().raw().toBuffer({resolveWithObject:true});let green=0;for(let k=0;k<130*100*4;k+=4){const r=data[k],g=data[k+1],b=data[k+2];if(r>155&&r<225&&g>225&&b>200&&g-r>20)green++;}if(green>12){await page.keyboard.press('k');received=true;break;}}
 expect(received).toBe(true);await expect(page.locator('#training-stats')).toContainText('24伤害');await expect(page.locator('#training-stats')).toContainText('命中1/3');const state=await page.evaluate(()=>(window as any).__farwind());expect(state.feedback).toBeUndefined();expect(state.session).toBeUndefined();expect(errors).toEqual([]);await mkdir('docs/parry-feedback-v3/evidence',{recursive:true});await page.screenshot({path:'docs/parry-feedback-v3/evidence/production.png'});await writeFile('docs/parry-feedback-v3/evidence/production.json',JSON.stringify({说明:'实际生产构建，真实K与画布右键扣费；依据正常比例截图提示起按，不按J仍实际反斩24伤害；开发对照参数不改变生产反馈，战斗诊断不暴露。',页面错误:errors,训练:await page.locator('#training-stats').textContent()},null,2));
});
