import {describe,it,expect} from 'vitest';
import {CombatFeedback,FEEDBACK,parryContactPoint,deflectDirection,feedbackVisual,feedbackAudio,audibleFeedback,type FeedbackEvent} from '../src/game/systems/combatFeedback';
import {synthFeedback,FEEDBACK_AUDIO} from '../src/game/systems/feedbackAudio';
import {CombatController,PARRY,COMBAT,STRIKES,attackConfig,type Attack} from '../src/game/systems/combat';
import {counterVisual,parryWeapon} from '../src/data/animation';
import {WeaponTrail} from '../src/game/systems/weaponTrail';
import {Sound} from '../src/game/systems/audio';
import sharp from 'sharp';
const fact=(id='one',kind:FeedbackEvent['kind']='parry-contact',at=0,until=600):FeedbackEvent=>({id,kind,at,until,targetId:'slime-1',attackId:id,point:{x:10,y:10},incoming:{x:0,y:1},blade:{x:1,y:0},deflect:{x:1,y:-.2},quality:'normal',material:'slime',alive:true});
const attack=(facing:0|1|2|3=0,id=1):Attack=>({id,start:0,stage:1,facing,hit:new Set(),counter:'normal',automatic:true,primaryTarget:'main',config:attackConfig({stage:1,counter:'normal'})});
describe('第三轮事实、去重、时钟和生命周期',()=>{
 it('同一接触只消费一次，紧接的不同攻击不被全局节流吞掉',()=>{const f=new CombatFeedback();expect(f.emit(fact())).toBe(true);expect(f.emit(fact())).toBe(false);expect(f.emit(fact('two','parry-contact',1))).toBe(true);expect(f.drain()).toHaveLength(2);expect(f.drain()).toHaveLength(0);expect(f.effects).toHaveLength(2);});
 it('快照冻结且深拷贝来招、位置和方向',()=>{const f=new CombatFeedback(),e=fact();f.emit(e);(e.point as any).x=999;(e.deflect as any).x=999;expect(f.history[0].point.x).toBe(10);expect(f.history[0].deflect.x).toBe(1);expect(Object.isFrozen(f.history[0])).toBe(true);expect(Object.isFrozen(f.history[0].blade)).toBe(true);});
 it('余势只轻量承接，不产生拨开、反斩或完整成功',()=>{const f=new CombatFeedback();f.emit(fact('after','afterguard'));f.advance(20);expect(f.drain().map(e=>e.kind)).toEqual(['afterguard']);expect(f.reaction('slime-1',0,'slime')).toBeNull();f.advance(65);expect(f.effects).toEqual([]);});
 it('拨开只在实际动作进度20毫秒到达后一次性发出，停顿不前进',()=>{const f=new CombatFeedback();f.emit(fact());f.drain();for(let i=0;i<10;i++)f.advance(0);expect(f.drain()).toEqual([]);f.advance(19.999);expect(f.drain()).toEqual([]);f.advance(20);expect(f.drain().map(e=>[e.kind,e.at])).toEqual([['deflect-release',20]]);f.advance(21);expect(f.drain()).toEqual([]);});
 it('真实受伤打断尚未拨开的动作，不补放释放声，已成立的接触闪及敌人受力保留',()=>{const f=new CombatFeedback();f.emit(fact());f.drain();f.cancelRelease();f.advance(25);expect(f.drain()).toEqual([]);expect(f.effects).toHaveLength(1);expect(f.reaction('slime-1',25,'slime')).not.toBeNull();});
 it('破风随正式反斩起势20毫秒先于55毫秒有效段，不与命中瞬态抢同一起音',()=>{const f=new CombatFeedback();f.emit(fact('start','counter-start',60));f.drain();f.advance(79,'start');expect(f.drain()).toEqual([]);f.advance(80,'start');expect(f.drain().map(e=>[e.kind,e.at])).toEqual([['counter-swing',80]]);f.advance(115,'start');expect(f.drain()).toEqual([]);});
 it('反斩起势前被取消，不补放计划中的破风声',()=>{const f=new CombatFeedback();f.emit(fact('start','counter-start',60));f.drain();f.advance(75,null);f.advance(100,null);expect(f.drain()).toEqual([]);expect(f.snapshot().delayed).toBe(0);});
 it('重置清空声音待发、闪光、延迟拨开和敌人反应；下一会话同编号合法',()=>{const f=new CombatFeedback();f.emit(fact());f.reset();f.advance(1000);expect(f.drain()).toEqual([]);expect(f.effects).toEqual([]);expect(f.reaction('slime-1',0,'slime')).toBeNull();expect(f.emit(fact())).toBe(true);});
 it('死亡后未结束的旧敌人攻击不补放出手声，远处攻击不冒充身边来招',()=>{const f=new CombatFeedback();f.reset(100);expect(f.attackAudible(99,{x:0,y:0},{x:0,y:0})).toBe(false);expect(f.attackAudible(100,{x:0,y:0},{x:0,y:0})).toBe(true);expect(f.attackAudible(101,{x:610,y:0},{x:0,y:0})).toBe(false);f.reset(0);expect(f.attackAudible(0,{x:0,y:0},{x:0,y:0})).toBe(true);});
 it('大量事件对象、反应及待处理反馈有数量上限',()=>{const f=new CombatFeedback();for(let i=0;i<200;i++)f.emit({...fact(String(i)),targetId:String(i)});expect(f.history.length).toBe(FEEDBACK.history);expect(f.effects.length).toBe(FEEDBACK.effects);expect(f.drain().length).toBeLessThanOrEqual(FEEDBACK.history);expect(f.snapshot().reactions).toBe(FEEDBACK.reactions);f.advance(1000);expect(f.effects).toEqual([]);expect(f.snapshot().delayed).toBe(0);});
 for(const mode of ['A','B','C','D'] as const)it(`${mode}开关只有声音和呈现，不改正式攻击配置`,()=>{expect(feedbackAudio(mode)).toBe(mode==='B'||mode==='D');expect(feedbackVisual(mode)).toBe(mode==='C'||mode==='D');const a=attack(),old=structuredClone(a.config);counterVisual(a,75,feedbackVisual(mode));expect(a.config).toEqual(old);});
});
describe('受力与方向性接触',()=>{
 it('成功第一帧非零受力，60毫秒到峰值，600和800总时长不影响起势',()=>{for(const until of [600,800]){const f=new CombatFeedback();f.emit(fact('p','parry-contact',0,until));expect(f.reaction('slime-1',0,'slime')!.strength).toBe(.55);expect(f.reaction('slime-1',30,'slime')!.strength).toBeGreaterThan(.85);expect(f.reaction('slime-1',60,'slime')!.strength).toBe(1);expect(f.reaction('slime-1',until-80,'slime')!.phase).toBe('recover');expect(f.reaction('slime-1',until,'slime')).toBeNull();}});
 it('反斩命中仅增加短促次级反应，不重启首次冲击或改变截止',()=>{const f=new CombatFeedback();f.emit(fact());f.emit(fact('cut','counter-hit',115));expect(f.reaction('slime-1',115,'slime')!.phase).toBe('unbalanced');expect(f.reaction('slime-1',115,'slime')!.secondary).toBe(1);expect(f.reaction('slime-1',210,'slime')!.secondary).toBe(0);expect(f.reaction('slime-1',600,'slime')).toBeNull();expect(f.history[0].until).toBe(600);});
 it('死亡命中仍有切入事件，立即清理存活踉跄，不播恢复',()=>{const f=new CombatFeedback();f.emit(fact());f.emit({...fact('fatal','counter-hit',115),alive:false});expect(f.reaction('slime-1',120,'leaf')).toBeNull();expect(f.drain().at(-1)!.kind).toBe('counter-hit');});
 for(const facing of [0,1,2,3] as const)it(`四向${facing}接触点在防御刃合法段、拨开方向随来招变化`,()=>{const w=parryWeapon(facing,1),root={x:850,y:720},c=parryContactPoint(root,w,{x:870,y:650}),d=deflectDirection({x:1,y:0},c.blade),d2=deflectDirection({x:0,y:1},c.blade);const length=Math.hypot(w.tip.x-w.grip.x,w.tip.y-w.grip.y),distance=Math.hypot(c.point.x-root.x-w.grip.x,c.point.y-root.y-w.grip.y);expect(distance/length).toBeGreaterThanOrEqual(.25-1e-7);expect(distance/length).toBeLessThanOrEqual(.85+1e-7);expect(Math.hypot(d.x-d2.x,d.y-d2.y)).toBeGreaterThan(.1);});
});
describe('反斩真实姿态与武器历史',()=>{
 it('首个有效姿态已经进入出刀方向，不能仍在身后蓄势；有效期自身有至少24像素真实扫掠',()=>{for(const facing of [0,1,2,3] as const){const a=attack(facing),w=counterVisual(a,55).weapon!;if(facing===0)expect(w.tip.y).toBeGreaterThan(w.grip.y);if(facing===1)expect(w.tip.y).toBeLessThan(w.grip.y-15);if(facing===2)expect(w.tip.x).toBeLessThan(w.grip.x-20);if(facing===3)expect(w.tip.x).toBeGreaterThan(w.grip.x+20);const tips=[55,84,113,142].map(t=>counterVisual(a,t).weapon!.tip);const path=tips.slice(1).reduce((n,p,i)=>n+Math.hypot(p.x-tips[i].x,p.y-tips[i].y),0);expect(path).toBeGreaterThan(24);}});
 for(const facing of [0,1,2,3] as const)it(`固定根四向${facing}仍有局部扫掠，轨迹与当前实际剑尖相同`,()=>{const a=attack(facing),trail=new WeaponTrail();for(let t=55;t<170;t++)trail.update(t,a,{x:850,y:720},0);const tips=trail.samples.map(s=>s.tip),length=tips.slice(1).reduce((n,p,i)=>n+Math.hypot(p.x-tips[i].x,p.y-tips[i].y),0);expect(new Set(tips.map(p=>`${p.x}/${p.y}`)).size).toBeGreaterThanOrEqual(4);expect(length).toBeGreaterThan(35);for(const s of trail.samples){const w=counterVisual(a,s.at).weapon!;expect(s.tip.x).toBeCloseTo(850+w.tip.x,6);expect(s.tip.y).toBeCloseTo(720+w.tip.y,6);}expect(a.config).toEqual(attackConfig({stage:1,counter:'normal'}));});
 it('左右镜像只反转局部横坐标，四个有效姿态相同身份',()=>{for(let t=55;t<170;t+=5){const l=counterVisual(attack(2),t),r=counterVisual(attack(3),t);expect(l.frame).toBe(r.frame);expect(l.weapon!.tip.x).toBe(-r.weapon!.tip.x);expect(l.weapon!.tip.y).toBe(r.weapon!.tip.y);expect(l.weapon!.grip.x).toBe(-r.weapon!.grip.x);}});
 it('不同攻击实例与会话的刀光不连接',()=>{const trail=new WeaponTrail();trail.update(100,attack(0,1),{x:850,y:720},0);trail.update(130,attack(0,2),{x:850,y:720},0);expect(trail.segments(130).every(s=>s.a.id===s.b.id)).toBe(true);trail.update(131,null,{x:850,y:720},1);expect(trail.samples).toEqual([]);});
 it('固定根图集可解码、透明、每个姿态剑尖有真实像素',async()=>{const {data,info}=await sharp('public/assets/animation/hero-counter-v3.png').ensureAlpha().raw().toBuffer({resolveWithObject:true});expect([info.width,info.height]).toEqual([960,480]);for(const facing of [0,1,2,3] as const)for(const t of [20,55,84,113,142,170]){const v=counterVisual(attack(facing),t),tip=v.weapon!.tip,x=Math.round(80+tip.x*160/145*(facing===2?-1:1)),y=Math.round(154+tip.y*160/145);let count=0;for(let dx=-4;dx<=4;dx++)for(let dy=-4;dy<=4;dy++){const px=v.frame%6*160+x+dx,py=Math.floor(v.frame/6)*160+y+dy;if(px>=0&&py>=0&&px<960&&py<480&&data[(py*info.width+px)*4+3]>20)count++;}expect(count,`${facing}/${t}真实剑尖像素`).toBeGreaterThan(2);}});
});
describe('正式攻击事实与音色身份',()=>{
 it('成功截住的同帧冲撞不盖住金属声，其他敌人威胁不被压掉且不依赖事件顺序',()=>{const main={...fact('来招','enemy-strike'),attackId:'主来招'},other={...fact('其他来招','enemy-strike'),attackId:'其他来招'},parry={...fact('成功','parry-contact'),attackId:'主来招'};for(const events of [[main,other,parry],[parry,other,main]]){expect(audibleFeedback(events)).not.toContain(main);expect(audibleFeedback(events)).toContain(other);expect(audibleFeedback(events)).toContain(parry);expect(events).toHaveLength(3);}expect(audibleFeedback([main])).toEqual([main]);});
 it('余势只截住对应来招声音，不把其他方向的真实威胁一起静音',()=>{const a={...fact('余势来招','enemy-strike'),attackId:'余势来招'},b={...fact('背后来招','enemy-strike'),attackId:'背后来招'},guard={...fact('余势','afterguard'),attackId:'余势来招'};expect(audibleFeedback([a,b,guard])).toEqual([b,guard]);});
 for(const scenario of ['hit','far','wall','dead','cancel'] as const)it(`${scenario}只在正式应用伤害之后发命中，挥出与命中分离`,()=>{const c=new CombatController(),f=new CombatFeedback(),p={x:0,y:0},e={id:'main',x:0,y:scenario==='far'?300:50,hp:scenario==='dead'?0:48};c.attack=attack();if(scenario==='cancel')c.hurt();c.update(0,170,0,p,[e],()=>false,()=>scenario!=='wall',(_e,_s,a)=>{e.hp-=attackConfig(a).damage;f.emit(fact('hit','counter-hit',55));},()=>{},()=>f.emit(fact('swing','counter-swing',55)));expect(f.history.filter(e=>e.kind==='counter-hit')).toHaveLength(scenario==='hit'?1:0);expect(f.history.filter(e=>e.kind==='counter-swing')).toHaveLength(scenario==='cancel'?0:1);});
 it('窗口、伤害、退款、取消、停顿、失衡及第四刀配置仍是实际基线',()=>{expect([PARRY.precise,PARRY.active,PARRY.normal.stop,PARRY.perfect.stop,PARRY.resume,PARRY.counter.windup,PARRY.normal.stagger,PARRY.perfect.stagger]).toEqual([90,240,55,75,60,55,600,800]);expect([PARRY.normal.damage,PARRY.perfect.damage,PARRY.cost,PARRY.bonus]).toEqual([24,30,12,6]);expect(STRIKES.map(s=>s.damage)).toEqual([18,20,30]);expect(COMBAT.hitStop).toEqual([36,36,58]);const c=new CombatController();c.swordWindEnabled=true;expect(c.maxStage).toBe(4);});
 it('三种原同声运动事件现在具有不同PCM内容与包络',()=>{const sounds=['enemy-strike','deflect-release','counter-swing'].map(k=>synthFeedback(k as any));expect(sounds[0].length).not.toBe(sounds[1].length);expect(sounds[1].length).not.toBe(sounds[2].length);expect(Array.from(sounds[0].slice(0,200))).not.toEqual(Array.from(sounds[2].slice(0,200)));});
 it('普通和精准同一撞击身份，起音硬、留有峰值余量、精准不是仅提高音量',()=>{const sounds=['parry-contact','parry-perfect-contact'].map(k=>synthFeedback(k as any));for(const s of sounds){expect(Math.max(...s.map(Math.abs))).toBeCloseTo(FEEDBACK_AUDIO.peak,5);const early=s.slice(0,960);expect(Math.max(...early.map(Math.abs))).toBeGreaterThan(.2);expect(s[0]).toBe(0);}expect(Array.from(sounds[0])).not.toEqual(Array.from(sounds[1]));});
 it('三份同身份变体不改变起音、长度或质量身份，材质只改变命中',()=>{const a=synthFeedback('counter-hit','slime'),b=synthFeedback('counter-hit','leaf'),variants=[0,1,2].map(v=>synthFeedback('parry-contact','slime',v));expect(a.length).toBe(b.length);expect(Array.from(a)).not.toEqual(Array.from(b));expect(new Set(variants.map(s=>s.length)).size).toBe(1);expect(variants.every(s=>s[0]===0)).toBe(true);expect(Array.from(variants[0])).not.toEqual(Array.from(variants[1]));});
 it('无AudioContext或静音只停止声音，不读取或修改战斗判定',()=>{const sound=new Sound(),c=new CombatController(),p={stamina:100};sound.volume=0;sound.feedback(fact(),'D');c.requestParry(0,0);c.flushActions(0,p);expect(c.parryQuality(10)).toBe('perfect');expect(p.stamina).toBe(88);expect(sound.diagnostic().voices).toBe(0);sound.clearFeedback();});
});
