import {describe,it,expect} from 'vitest';
import {RUNES,RUNE_CODEX,DUOS,RUNE_LOADOUTS,resolveDuos,RUNE_BALANCE as B,runeById,RETURN_RUNE} from '../src/data/runes';
import {initialState,validate,parseSave} from '../src/game/systems/state';
import {initialRunes,validateRunes,runeSnapshot,acquisitionReady,grantMilestoneRunes} from '../src/game/systems/runeState';
import {RuneCombat,type RuneTarget,type RuneEvent} from '../src/game/systems/runeCombat';
import {resolveDamage} from '../src/game/systems/damage';
import {outgoingDamage} from '../src/game/systems/economy';
import {STRIKES,CombatController,COMBAT} from '../src/game/systems/combat';
import {resolveSwordWindConfig} from '../src/data/swordWind';
import {StateCommit} from '../src/game/systems/stateCommit';
import {ENCOUNTERS} from '../src/data/maps/windbell/encounters';
import {props,solidPropAt,terrainBlocked,propBounds} from '../src/data/world';
import {HOMES} from '../src/data/npcLife';
import {motionBlocked,clearMotionLine} from '../src/game/systems/obstacles';
import {mkdirSync,writeFileSync} from 'node:fs';
import {settleEncounterDeath} from '../src/game/systems/encounterState';
const safe={combat:false,boss:false,defense:false,trial:false,story:false,action:false};
function harness(slots:string[],boss=false){const s=initialState();s.runes.owned=RUNES.map(r=>r.id);s.runes.slots=[...slots,...Array(5-slots.length).fill(null)];s.player.x=0;s.player.y=0;const enemies:RuneTarget[]=[{id:'e1',x:55,y:0,hp:100000,boss:boss?'boss':undefined}],receipts:RuneEvent[]=[];let kills=0,pushes=0;let wall=false;
 const engine=new RuneCombat({state:()=>s,targets:()=>enemies,A:()=>outgoingDamage(s,STRIKES[0].damage),clear:()=>true,visible:()=>true,blocker:()=>wall?{t:.4}:null,push:(e,d,n)=>{pushes++;if(e.boss)return 'immune';e.x+=d.x*n;e.y+=d.y*n;return 'moved';},damage:(e,ev)=>{const hit=resolveDamage({sourceId:'player',targetId:e.id,attackId:ev.eventId,amount:ev.amount,sourceType:ev.sourceKind==='phantom'?'player-phantom':'player-rune',eventId:null},{id:'player',hp:s.player.hp,faction:'village',armor:0},{id:e.id,hp:e.hp,faction:'hostile',armor:0});if(hit.applied){e.hp=hit.hp;receipts.push({...ev,actual:hit.damage});if(hit.killed)kills++;}return hit;},sound:()=>{},checkpoint:()=>{}});engine.random=()=>.999;
 let seq=0;function hit(stage=1,instance?:string,e=enemies[0]){const ev=engine.native(instance??`hit:${++seq}`,e,outgoingDamage(s,STRIKES[stage===4?0:stage-1].damage),stage,stage===4);const receipt=resolveDamage({sourceId:'player',targetId:e.id,attackId:ev.eventId,amount:ev.amount,sourceType:'player-melee',eventId:null},{id:'player',hp:s.player.hp,faction:'village',armor:0},{id:e.id,hp:e.hp,faction:'hostile',armor:0});if(receipt.applied){e.hp=receipt.hp;engine.nativeLanded(e,ev,receipt.damage);}return ev;}
 function advance(ms:number){for(let at=0;at<ms;at+=20)engine.advance(Math.min(20,ms-at));}
 return {s,engine,enemies,receipts,hit,advance,get A(){return engine.ctx.A();},get kills(){return kills;},get pushes(){return pushes;},setWall(v:boolean){wall=v;}};
}
describe('符文图鉴、五槽与保存',()=>{
 it('保留旧30枚并新增3枚／34图鉴／15联动 与品阶配额，所有资源映射完整',()=>{expect(RUNES).toHaveLength(33);expect(RUNE_CODEX).toHaveLength(34);expect(DUOS).toHaveLength(15);expect(new Set(RUNE_CODEX.map(r=>r.id)).size).toBe(34);expect(new Set(DUOS.map(d=>d.id)).size).toBe(15);expect(['low','mid','high','legend'].map(t=>RUNES.filter(r=>r.tier===t).length)).toEqual([13,8,7,5]);for(const r of RUNES){expect(r.name&&r.description&&r.trigger&&r.visual&&r.sound).toBeTruthy();expect(Object.keys(r.config).length).toBeGreaterThan(0);}});
 it('旧档只补固定归风与五个空槽，不改其他进度',()=>{const s=initialState();s.player.hp=73;const old=structuredClone(s) as any;old.schema_version=15;delete old.runes;const next=validate(old);expect(next.runes).toEqual(initialRunes());for(const key of ['skills','bag','equipment','fieldQuests','encounters','life','xiaobao','quest','player'] as const)expect(next[key]).toEqual(s[key]);expect(next.runes.owned).toEqual([]);});
 it('归风固定、五自由槽、不能重复，五绝世同时合法',()=>{const s=initialState();s.runes.owned=RUNES.map(r=>r.id);expect(()=>runeSnapshot(s,{kind:'equip',slot:5,id:null},safe)).toThrow('归风');let next=s;for(let i=0;i<5;i++)next=runeSnapshot(next,{kind:'equip',slot:i,id:`r${26+i}`},safe);expect(validate(next).runes.slots).toEqual(RUNE_LOADOUTS[5].slots);expect(()=>runeSnapshot(next,{kind:'equip',slot:0,id:'r27'},safe)).toThrow('同名');expect(()=>validateRunes({...next.runes,fixed:null})).toThrow();});
 it.each(['combat','boss','defense','trial','story','action'] as const)('锁定条件 %s 阻止换装但不损失收藏',key=>{const s=initialState();s.runes.owned=['r01'];expect(()=>runeSnapshot(s,{kind:'equip',slot:0,id:'r01'},{...safe,[key]:true})).toThrow();expect(s.runes.slots).toEqual(Array(5).fill(null));});
 it('三套预设保存和载入不返还冷却',()=>{let s=initialState();s.runes.owned=['r26'];s.runes.cooldowns.r26=19300;s=runeSnapshot(s,{kind:'equip',slot:0,id:'r26'},safe);s=runeSnapshot(s,{kind:'preset-save',index:1},safe);s=runeSnapshot(s,{kind:'equip',slot:0,id:null},safe);s=runeSnapshot(s,{kind:'preset-load',index:1},safe);expect(s.runes.slots[0]).toBe('r26');expect(s.runes.cooldowns.r26).toBe(19300);});
 it('保存失败不发布装备或扣款副本',async()=>{const s=initialState();s.runes.owned=['r01'];const c=new StateCommit();let published=false;await expect(c.run(()=>s,current=>runeSnapshot(current,{kind:'equip',slot:0,id:'r01'},safe),async()=>{throw Error('保存失败');},()=>{published=true;})).rejects.toThrow('保存失败');expect(published).toBe(false);expect(s.runes.slots[0]).toBeNull();});
 it('凰心与绝世冷却跨保存、读取、卸装保留',()=>{const h=harness(['r26','r27','r28','r29','r30']);h.engine.damaged(h.enemies[0],0,100);h.engine.startCooldown('r26',20000);h.advance(400);const loaded=parseSave(JSON.stringify(validate(h.s)));expect(loaded.runes.cooldowns.r30).toBe(179600);expect(loaded.runes.cooldowns.r26).toBe(19600);const next=runeSnapshot(loaded,{kind:'equip',slot:4,id:null},safe);expect(next.runes.cooldowns.r30).toBe(179600);});
});
describe('能力配方',()=>{
 it.each(RUNE_LOADOUTS.map((l,i)=>[l.name,l.slots,[['d01','d13'],['d02'],['d03','d12'],['d04','d05','d06','d07'],['d08','d09','d10'],['d01','d11','d13','d14','d15']][i]]))('%s 精确激活配方',(name,slots,expected)=>{expect(resolveDuos(slots as string[],true).filter(d=>d.active).map(d=>d.id)).toEqual(expected);});
 it('雷击不代替感电，猎星不代替追踪，厄印不代替刃涡',()=>{for(const [slots,id] of [[['r01','r03'],'d06'],[['r01','r06'],'d14'],[['r04','r06'],'d03']] as const)expect(resolveDuos(slots,false).find(d=>d.id===id)!.active).toBe(false);expect(resolveDuos(['return-wind','r01'],true).filter(d=>d.active)).toEqual([]);});
 it('多个同能力提供者只激活一条共鸣并显示所有提供者',()=>{const d=resolveDuos(RUNE_LOADOUTS[1].slots,true).filter(d=>d.active);expect(d).toHaveLength(1);expect(d[0].providers.mirror).toHaveLength(3);expect(d[0].providers.doom).toHaveLength(2);});
 it('未正式学习剑风不能激活潮影或释放寒晶、回澜',()=>{const h=harness(['r20','r21','r26']);expect(resolveDuos(h.s.runes.slots,false).find(d=>d.id==='d11')!.active).toBe(false);h.engine.windRelease('wind',h.s.player,{x:1,y:0},resolveSwordWindConfig());h.advance(1000);expect(h.engine.fields).toEqual([]);expect(h.engine.projectiles).toEqual([]);});
});
describe('纵向切片与合法连锁',()=>{
 it('A 从真实战斗配置与武器读取，符文、防御、暴击各一次',()=>{const h=harness(['r01']);h.s.equipment.weapon='ironSword';const A=outgoingDamage(h.s,STRIKES[0].damage);expect(h.A).toBe(A);h.hit();h.advance(180);expect(h.receipts[0].actual).toBeCloseTo(A*.25);expect(h.engine.metrics.native).toBe(1);});
 it('潮汐→海啸雷狱→雷击→感电，位移免疫仍成立',()=>{const h=harness(RUNE_LOADOUTS[0].slots,true);h.hit();h.advance(180);const tide=h.receipts.find(r=>r.tags.includes('tide_hit'))!,thunder=h.receipts.find(r=>r.sourceDuoId==='d01')!;expect(tide).toBeTruthy();expect(thunder.amount).toBeCloseTo(h.A*.4);expect(thunder.rootEventId).toBe(tide.rootEventId);expect(thunder.parentEventId).toBe(tide.eventId);expect(thunder.procDepth).toBe(2);expect(h.engine.statuses.get('e1')!.jolt).toBeTruthy();expect(h.receipts.some(r=>r.tags.includes('compensation_hit'))).toBe(true);expect(h.engine.metrics.native).toBe(1);});
 it('雷击有预兆，落雷前或离开落点不扣血',()=>{const h=harness(['r01']);h.hit();h.advance(100);expect(h.receipts).toHaveLength(0);h.enemies[0].x+=100;h.advance(100);expect(h.receipts).toHaveLength(0);});
 it('雾场→雷酿风暴→感电，不冒充原生命中',()=>{const h=harness(RUNE_LOADOUTS[3].slots);h.hit(3);h.advance(920);expect(h.receipts.some(r=>r.tags.includes('mist_tick'))).toBe(true);expect(h.receipts.some(r=>r.sourceDuoId==='d05'&&r.tags.includes('lightning_hit'))).toBe(true);expect(h.engine.statuses.get('e1')!.jolt).toBeTruthy();expect(h.engine.metrics.native).toBe(1);expect(h.engine.statuses.get('e1')!.chill!.stacks).toBeGreaterThan(1);});
 it('冲刺镜弧提前引爆厄印，倒计时彻底取消',()=>{const h=harness(RUNE_LOADOUTS[1].slots);h.hit();h.advance(150);h.hit();h.engine.dashStart('dash');h.s.player.x=45;h.advance(20);const doom=h.receipts.filter(r=>r.tags.includes('doom_hit'));expect(doom).toHaveLength(1);expect(doom[0].sourceDuoId).toBe('d02');expect(doom[0].amount).toBeCloseTo(h.A*(.8+.2+.3));expect(h.engine.statuses.get('e1')!.doom).toBeUndefined();h.advance(1200);expect(h.receipts.filter(r=>r.tags.includes('doom_hit'))).toHaveLength(1);});
 it('三向、多段、多敌只蓄积一次，状态逐目标生效',()=>{const h=harness(['r11','r26','r27','r03']);h.enemies.push({id:'e2',x:80,y:15,hp:100000});for(let i=0;i<6;i++){for(const e of h.enemies)h.hit(1,'one-instance',e);}expect(h.s.runes.counts.r26).toBe(1);expect(h.s.runes.counts.r27).toBe(1);expect(h.s.runes.counts.r11).toBe(1);expect(h.engine.statuses.get('e1')!.chill!.stacks).toBe(1);expect(h.engine.statuses.get('e2')!.chill!.stacks).toBe(1);});
 it('追踪刃涡同时追踪、施寒、暴击，不能再生追踪剑',()=>{const h=harness(RUNE_LOADOUTS[2].slots);h.engine.random=()=>0;h.hit(3);const count=h.engine.projectiles.filter(p=>p.kind==='seeking').length;expect(count).toBe(2);const v=h.engine.projectiles.find(p=>p.kind==='vortex')!;expect(v.radius).toBeCloseTo(58*.85);expect(v.canCrit).toBe(true);h.enemies[0].y=20;h.advance(700);const hits=h.receipts.filter(r=>r.tags.includes('vortex_hit'));expect(hits.length).toBeGreaterThan(0);expect(hits.every(r=>r.critical)).toBe(true);expect(h.engine.statuses.get('e1')?.chill?.stacks).toBeGreaterThan(0);expect(h.engine.metrics.native).toBe(1);expect(h.s.runes.counts.r26).toBe(1);expect(h.engine.projectiles.filter(p=>p.kind==='seeking').length).toBeLessThanOrEqual(count);});
 it('刃涡频率限制，遇墙终止，不穿墙追踪',()=>{const h=harness(['r22','r06','r03']);h.hit(3);h.advance(1000);expect(h.receipts.filter(r=>r.tags.includes('vortex_hit')).length).toBeLessThanOrEqual(4);const w=harness(['r22','r06','r03']);w.setWall(true);w.hit(3);w.advance(20);expect(w.engine.projectiles.some(p=>p.kind==='vortex')).toBe(false);});
 it('追踪箭剑命中才留雷针，刃涡不留，雷针延迟不循环',()=>{const h=harness(['r01','r15','r22','r06']);h.engine.random=()=>0;h.hit(3);h.advance(300);const arrow=h.receipts.find(r=>r.tags.includes('seeking_projectile_hit'));expect(arrow).toBeTruthy();expect(h.receipts.filter(r=>r.sourceDuoId==='d14')).toHaveLength(0);h.advance(800);expect(h.receipts.some(r=>r.sourceDuoId==='d14')).toBe(true);expect(h.engine.metrics.native).toBe(1);expect(h.s.runes.counts.r26).toBeUndefined();});
 it('正式三向剑风复制一组共享去重的潮影，不复制自己',()=>{const h=harness(['r20','r26']);h.s.skills.swordWindStage=5;h.engine.rebind();h.engine.windRelease('wind-five',h.s.player,{x:1,y:0},resolveSwordWindConfig(5));h.advance(140);expect(h.engine.projectiles.filter(p=>p.kind==='phantom')).toHaveLength(3);const phantom=h.engine.projectiles.filter(p=>p.kind==='phantom');expect(phantom[0].hit).toBe(phantom[1].hit);h.advance(1200);expect(h.receipts.filter(r=>r.tags.includes('phantom_hit')).length).toBeLessThanOrEqual(1);expect(h.engine.metrics.native).toBe(0);expect(h.engine.jobs).toHaveLength(0);});
 it('去程与返程独立去重，各程最多命中同目标一次',()=>{const h=harness(['r20']);h.s.skills.swordWindStage=1;h.engine.rebind();h.engine.windRelease('wind-return',h.s.player,{x:1,y:0},resolveSwordWindConfig());h.advance(1300);expect(h.receipts.filter(r=>r.tags.includes('tide_hit'))).toHaveLength(2);});
});
describe('状态规则与防御',()=>{
 it('酿毒五／八／十一层，虚弱到期超额立刻裁回八，跳伤时刻保留',()=>{const h=harness(RUNE_LOADOUTS[4].slots);for(let i=0;i<15;i++)h.hit();let p=h.engine.statuses.get('e1')!.poison!;expect(p.stacks).toBe(11);h.advance(2600);const parent=h.engine.parent('r05','mist_tick',h.enemies[0]);h.engine.poison(h.enemies[0],parent);const next=p.next;h.advance(450);p=h.engine.statuses.get('e1')!.poison!;expect(p.stacks).toBe(8);expect(p.until).toBe(5600);expect(p.next).toBeGreaterThanOrEqual(next);});
 it('仅酿毒由 0.5 加速为 0.35，持续、单跳伤害不变',()=>{const normal=harness(['r05']),fast=harness(['r05','r04']);normal.hit();fast.hit();normal.advance(1050);fast.advance(1050);expect(normal.receipts.filter(r=>r.tags.includes('poison_tick'))).toHaveLength(2);expect(fast.receipts.filter(r=>r.tags.includes('poison_tick'))).toHaveLength(3);expect(fast.receipts.filter(r=>r.tags.includes('doom_hit'))).toHaveLength(1);expect(normal.receipts[0].amount).toBeCloseTo(fast.receipts.find(r=>r.tags.includes('poison_tick'))!.amount);normal.advance(2100);expect(normal.engine.statuses.get('e1')!.poison).toBeUndefined();});
 it('寒雷长劫保留感电，每次出手受频率约束，四秒后过期',()=>{const h=harness(['r11','r03']);const parent=h.engine.parent('r11','lightning_hit',h.enemies[0]);h.engine.chain(h.enemies[0],parent);h.engine.enemyAttempt(h.enemies[0],'attack-1');h.advance(100);h.engine.enemyAttempt(h.enemies[0],'attack-2');h.advance(700);h.engine.enemyAttempt(h.enemies[0],'attack-3');expect(h.receipts.filter(r=>r.tags.includes('jolt_hit'))).toHaveLength(2);h.advance(3300);h.engine.enemyAttempt(h.enemies[0],'attack-4');expect(h.receipts.filter(r=>r.tags.includes('jolt_hit'))).toHaveLength(2);});
 it('基础感电仅放电一次，虚弱影响战斗攻击',()=>{const h=harness(['r11','r07']);h.hit();h.engine.chain(h.enemies[0],h.engine.parent('r11','lightning_hit',h.enemies[0]));h.engine.enemyAttempt(h.enemies[0],'attack-1');h.advance(800);h.engine.enemyAttempt(h.enemies[0],'attack-2');expect(h.receipts.filter(r=>r.tags.includes('jolt_hit'))).toHaveLength(1);expect(h.engine.enemyScale('e1')).toBe(.8);});
 it('绯毒猎杀暴击率、倍率与毒层上限使用同一计算',()=>{const h=harness(RUNE_LOADOUTS[4].slots);for(let i=0;i<12;i++)h.hit();expect(h.engine.critRate(h.enemies[0])).toBeCloseTo(.2+.25+.2);expect(h.engine.critMultiplier(h.enemies[0])).toBe(2.25);expect(h.engine.poisonCap('e1')).toBe(11);});
 it('五层寒冷可冰爆且有限冷却，Boss 减速限制',()=>{const h=harness(['r03','r13'],true);for(let i=0;i<5;i++)h.hit();expect(h.receipts.filter(r=>r.tags.includes('ice_hit'))).toHaveLength(1);for(let i=0;i<5;i++)h.hit();expect(h.receipts.filter(r=>r.tags.includes('ice_hit'))).toHaveLength(1);expect(h.engine.movementSlow(h.enemies[0])).toBe(.2);});
 it('格挡潮环继续引雷并提供短暂 Boss 减伤',()=>{const h=harness(['r02','r11','r08'],true);h.engine.block(false,'block',h.enemies[0]);h.advance(180);expect(h.receipts.some(r=>r.sourceDuoId==='d13'&&r.tags.includes('tide_hit'))).toBe(true);expect(h.receipts.some(r=>r.sourceDuoId==='d01')).toBe(true);expect(h.engine.incomingScale('e1',true)).toBe(.8);h.advance(3000);expect(h.engine.incomingScale('e1',true)).toBe(1);});
 it('轻羽真实风步消耗为 16，不改无敌窗口；御风转换不自增',()=>{const h=harness(['r09','r18']),c=new CombatController(),p={x:0,y:0,stamina:100};c.dashCostMultiplier=h.engine.dashCost();c.requestActions([{kind:'dash',at:0,sequence:1,axis:{x:1,y:0}}],0,p,3);c.flushActions(0,p);expect(p.stamina).toBe(84);expect(c.invulnerable(COMBAT.dash.invulnStart-1)).toBe(false);expect(c.invulnerable(COMBAT.dash.invulnEnd)).toBe(false);h.engine.dashStart('dash');const n=h.engine.nativeBonus(h.enemies[0]);expect(n).toBeCloseTo((.12+.15)*.8);for(let i=0;i<100;i++)expect(h.engine.nativeBonus(h.enemies[0])).toBe(n);});
});
describe('五绝世、冷却与生命周期',()=>{
 it('万剑常驻、剑域、十二个实际追踪判定，冷却中不蓄积',()=>{const h=harness(['r26']);for(let i=0;i<10;i++)h.hit();expect(h.engine.critRate(h.enemies[0])).toBe(.25);expect(h.engine.domainUntil).toBe(6000);expect(h.engine.nativeBonus(h.enemies[0])).toBe(.3);expect(h.s.runes.cooldowns.r26).toBe(20000);for(let i=0;i<20;i++)h.hit();expect(h.s.runes.counts.r26).toBe(0);h.advance(6800);expect(h.receipts.filter(r=>r.tags.includes('seeking_projectile_hit'))).toHaveLength(12);expect(h.engine.projectiles).toHaveLength(0);});
 it('九霄三轮天雷与最后范围雷柱，最多五目标',()=>{const h=harness(['r27']);for(let i=2;i<=7;i++)h.enemies.push({id:'e'+i,x:55+i*12,y:0,hp:100000});for(let i=0;i<8;i++)h.hit();h.advance(2400);expect(h.receipts.filter(r=>r.tags.includes('lightning_hit')).length).toBeGreaterThanOrEqual(22);expect(h.s.runes.cooldowns.r27).toBe(21600);expect(h.engine.metrics.native).toBe(8);});
 it('归墟六次合法 tide 脉冲和终结，Boss 不牵引',()=>{const h=harness(['r28','r27'],true);for(let i=0;i<3;i++)h.hit(3);const before=h.pushes;h.advance(3500);expect(h.receipts.filter(r=>r.tags.includes('tide_hit'))).toHaveLength(9);expect(h.receipts.filter(r=>r.tags.includes('collapse_hit'))).toHaveLength(1);expect(h.receipts.some(r=>r.sourceDuoId==='d01')).toBe(true);expect(h.pushes-before).toBe(6);expect(h.enemies[0].x).toBe(55);});
 it('时隙只回放原生实际伤害，总上限 600%A，位置与世界不回滚',()=>{const h=harness(['r29','r01']);h.engine.block(true,'perfect',h.enemies[0]);expect(h.engine.timeSlow(h.enemies[0])).toBe(.6);const boss={...h.enemies[0],boss:'boss'};expect(h.engine.timeSlow(boss)).toBe(.2);for(let i=0;i<20;i++)h.hit();h.advance(3100);const replay=h.receipts.filter(r=>r.tags.includes('replay_hit'));expect(replay.reduce((n,r)=>n+(r.actual??0),0)).toBeCloseTo(h.A*6);expect(h.s.player.x).toBe(0);expect(h.s.time).toBe(480);expect(h.engine.time).toBeUndefined();});
 it('凰心仅战斗伤害拦截死亡，镜羽不被无敌消耗，同帧不耗尽',()=>{const h=harness(['r30','r08']);expect(h.engine.damaged(h.enemies[0],0,100)).toBe(50);expect(h.engine.feathers).toBe(3);expect(h.engine.protectHit(h.enemies[0],'immune')).toBe(true);expect(h.engine.feathers).toBe(3);h.advance(1520);expect(h.engine.protectHit(h.enemies[0],'one')).toBe(true);expect(h.engine.feathers).toBe(2);expect(h.engine.protectHit(h.enemies[0],'same-frame')).toBe(true);expect(h.engine.feathers).toBe(2);h.advance(140);h.engine.protectHit(h.enemies[0],'two');h.advance(140);h.engine.protectHit(h.enemies[0],'three');expect(h.engine.feathers).toBe(0);h.advance(4800);expect(h.s.player.hp).toBe(68);expect(h.engine.damaged(h.enemies[0],0,100)).toBe(0);expect(h.engine.metrics.phoenix).toBe(1);});
 it('卸装、死亡、换场景清理所有攻击与临时增益，不返还冷却',()=>{const h=harness(RUNE_LOADOUTS[5].slots);for(let i=0;i<12;i++)h.hit(3);h.engine.block(true,'block',h.enemies[0]);h.engine.damaged(h.enemies[0],0,100);expect(h.engine.jobs.length+h.engine.fields.length).toBeGreaterThan(0);const cool={...h.s.runes.cooldowns};h.engine.clear();expect(h.engine.fields).toHaveLength(0);expect(h.engine.jobs).toHaveLength(0);expect(h.engine.projectiles).toHaveLength(0);expect(h.engine.feathers).toBe(0);expect(h.s.runes.cooldowns).toEqual(cool);const receipt=h.receipts.length;h.advance(4000);expect(h.receipts).toHaveLength(receipt);});
 it('已死目标不继续联动、扣血或重复奖励',()=>{const h=harness(['r01','r02','r11']);h.enemies[0].hp=h.A*.15;const ev=h.engine.parent('r02','tide_hit',h.enemies[0]);h.engine.apply(h.enemies[0],h.engine.child(ev,h.enemies[0],h.A*.2,['tide_hit'],'r02'));h.advance(2000);expect(h.kills).toBe(1);expect(h.receipts).toHaveLength(1);expect(h.engine.statuses.size).toBe(0);});
 it('低画质、降低闪光不改变任何战斗判定',()=>{const a=harness(RUNE_LOADOUTS[3].slots),b=harness(RUNE_LOADOUTS[3].slots);b.s.runes.settings={simple:true,lowFlash:true};for(let i=0;i<9;i++){a.hit(i%3+1);b.hit(i%3+1);a.advance(300);b.advance(300);}a.advance(4200);b.advance(4200);expect(a.engine.metrics).toEqual(b.engine.metrics);expect(a.enemies[0].hp).toBe(b.enemies[0].hp);expect(a.receipts.map(r=>[r.tags,r.amount])).toEqual(b.receipts.map(r=>[r.tags,r.amount]));});
});
describe('生产获取',()=>{
 it('30枚均映射现有可达世界对象、委托、商店或专属首领',()=>{for(const r of RUNES){const a=r.acquisition;if(a.kind==='explore')expect(props.some(p=>p.id===a.key)).toBe(true);if(a.kind==='encounter'||a.kind==='boss')expect(ENCOUNTERS.some(d=>d.id===a.key)).toBe(true);if(a.kind==='shop')expect(a.price).toBeGreaterThan(0);}expect(RUNES.filter(r=>r.tier==='legend').map(r=>r.acquisition.kind)).toEqual(['boss','boss','boss','boss','allBosses']);});
 it('正常采集自动获得雷触，背包不占格，历史迁移不补发全部',()=>{const before=initialState(),s=structuredClone(before);s.collected['wood-v1']=s.time;const earned=grantMilestoneRunes(s,before);expect(earned.map(r=>r.id)).toEqual(['r01']);expect(s.runes.owned).toEqual(['r01']);expect(s.bag).toEqual(before.bag);});
 it('基础商店真实扣款保存，重复购买与缺钱拒绝',()=>{const s=initialState();s.coins=40;const next=runeSnapshot(s,{kind:'claim',id:'r08',shop:'general'},safe);expect(next.coins).toBe(20);expect(next.runes.owned).toEqual(['r08']);expect(next.bag).toEqual(s.bag);expect(()=>runeSnapshot(next,{kind:'claim',id:'r08',shop:'general'},safe)).toThrow('已拥有');expect(()=>runeSnapshot({...s,coins:0},{kind:'claim',id:'r08',shop:'general'},safe)).toThrow();});
 it('专属 Boss 首次达成必得，旧 cleared 不冒充首领死亡',()=>{const before=initialState(),s=structuredClone(before),g=s.encounters.groups['west-wolf-den'];g.activated=true;for(const d of ENCOUNTERS.find(d=>d.id==='west-wolf-den')!.members)settleEncounterDeath(s.encounters,d.id,false);g.boss!.stage='defeated';expect(acquisitionReady(s,runeById('r26')!)).toBe(true);expect(grantMilestoneRunes(s,before).some(r=>r.id==='r26')).toBe(true);g.boss!.stage='legacy';expect(acquisitionReady(s,runeById('r26')!)).toBe(false);});
});

// 实机发现的回归路径：视觉只存坐标，不能把敌人精灵、监听或函数放进诊断快照。
describe('实机首因回归',()=>{
 it('特效端点按值快照，可结构化复制且不随敌人漂移',()=>{const h=harness(['r08']);const e={...h.enemies[0],sprite:{listener:()=>{}}};h.engine.fx('mirror-step',e,40,'r08',300,{end:e});e.x=999;const value=structuredClone(h.engine.snapshot());expect(value.effects[0].end.x).toBe(h.enemies[0].x);expect(Object.keys(value.effects[0].end)).toEqual(['x','y']);});
 it('村内任一实际木材节点都能首次获得雷触，零时刻也有效',()=>{const s=initialState(),before=structuredClone(s);s.collected['wood-yard-2']=0;expect(acquisitionReady(s,RUNES[0])).toBe(true);expect(grantMilestoneRunes(s,before).map(r=>r.id)).toContain('r01');});
 it('三向原生剑风仍只生成一出一返两道潮浪',()=>{const h=harness(['r20']);h.s.skills.swordWindStage=5;h.engine.rebind();h.engine.windRelease('wind-three',h.s.player,{x:1,y:0},resolveSwordWindConfig(5));expect(h.engine.projectiles.filter(p=>p.kind==='wave')).toHaveLength(1);h.advance(1800);expect(h.receipts.filter(r=>r.tags.includes('tide_hit'))).toHaveLength(2);});
});

it('所有探索符文有合法的实际交互站位',()=>{const rows=RUNES.filter(r=>r.acquisition.kind==='explore').map(r=>{const p=props.find(p=>p.id===r.acquisition.key)!;const candidates=[];for(let dx=-80;dx<=80;dx+=10)for(let dy=-80;dy<=80;dy+=10){const v={x:Math.round((p.x+dx)/10)*10,y:Math.round((p.y+dy)/10)*10};if(Math.hypot(v.x-p.x,v.y-p.y)<90&&[-6,0,6].every(x=>[-6,0,6].every(y=>!motionBlocked(v.x+x,v.y+y)))&&clearMotionLine(v,p,p.id))candidates.push(v);}expect(candidates.length,r.name+'的交互站位').toBeGreaterThan(0);return {符文:r.name,节点:p.id,坐标:{x:p.x,y:p.y},可交互站位:candidates};});mkdirSync('docs/runes/evidence',{recursive:true});writeFileSync('docs/runes/evidence/acquisition-geometry.json',JSON.stringify({说明:'实际地图、玩家脚部碰撞与正式交互视线的固定基准；仅代表站位合法，完整路线以实机记录为准。',记录:rows},null,2));});
it('命中生成的真实敌人场域只保存坐标',()=>{const h=harness(['r16']);const e={...h.enemies[0],sprite:{listener:()=>{}}};h.engine.field('mist',e,h.engine.parent('r16','finisher',e),'r16');expect(()=>structuredClone(h.engine.snapshot())).not.toThrow();expect(Object.keys(h.engine.fields[0].point)).toEqual(['x','y']);});

it('实机木桩后的脚部起点与药房站位使用当前碰撞',()=>{const home=HOMES.find(h=>h.id==='healer-home')!,points=[{x:850,y:660},{x:850,y:670},{x:850,y:690},{x:home.door.x,y:home.door.y+60}],rows=points.map(p=>({坐标:p,地形:terrainBlocked(p.x,p.y),物体:solidPropAt(p.x,p.y),脚部九点安全:[-6,0,6].every(x=>[-6,0,6].every(y=>!motionBlocked(p.x+x,p.y+y))),至南十像素线:clearMotionLine(p,{x:p.x,y:p.y+10})}));writeFileSync('docs/runes/evidence/room-geometry.json',JSON.stringify({说明:'实机失败追踪显示玩家脚部在 850,660；使用当前地图碰撞定位导航起点和交互目标的约束。',记录:rows,木桩:props.filter(p=>p.id==='training-dummy').map(p=>({节点:p,碰撞:propBounds(p,true)}))},null,2));expect(rows.at(-1)!.脚部九点安全).toBe(true);});

it('潮浪自身击退后落雷标记落在实际落脚处，普通敌人与 Boss 均可接雷潮',()=>{const h=harness(['r12','r11']);const e=h.enemies[0];h.engine.tide(e,h.engine.parent('r12','finisher',e),.65,'r12',50);expect(e.x).toBe(105);h.advance(180);expect(h.receipts.some(r=>r.sourceDuoId==='d01'&&r.tags.includes('lightning_hit'))).toBe(true);});
