import {test,expect} from '@playwright/test';
import {mkdir,writeFile} from 'node:fs/promises';
import {cpus,platform,release} from 'node:os';
import {initialState} from '../src/game/systems/state';
import {prepareRaid} from '../src/game/systems/defense';
const root=process.env.FARWIND_EVIDENCE_ROOT??'docs/village-defense/safety/integrated-current/performance';
test('一分钟正式速率防御短样本，记录帧间隔和堆内存，不声明长期稳定60帧',async({page,browser})=>{
 await mkdir(root,{recursive:true});await page.goto('/');const s=initialState();s.time=1260;Object.assign(s.player,{x:1940,y:1080});s.defense=prepareRaid(s.defense,{x:670,y:720},'east-gate',3);
 page.once('dialog',d=>d.accept());const chooser=page.waitForEvent('filechooser');await page.getByRole('button',{name:'导入存档',exact:true}).click();await(await chooser).setFiles({name:'safety-performance-initial.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(s))});await page.waitForFunction(()=>(window as any).__farwind().mode==='');
 const cdp=await page.context().newCDPSession(page),rows:any[]=[];
 const frames=page.evaluate(()=>new Promise<any>(resolve=>{let first=performance.now(),previous=first;const times:number[]=[],counts={事件怪:0,卫兵:0,箭:0};const watch=setInterval(()=>{const d=(window as any).__farwind();counts.事件怪=Math.max(counts.事件怪,d.defense.enemies.filter((e:any)=>e.hp>0).length);counts.卫兵=Math.max(counts.卫兵,d.state.defense.guards.filter((g:any)=>!g.dead).length);counts.箭=Math.max(counts.箭,d.defense.arrows.length);},250);function sample(at:number){times.push(at-previous);previous=at;if(at-first<60000)requestAnimationFrame(sample);else{clearInterval(watch);times.sort((a,b)=>a-b);resolve({时长毫秒:at-first,帧数:times.length,中位帧间隔:times[Math.floor(times.length*.5)],百分之95帧间隔:times[Math.floor(times.length*.95)],最大帧间隔:times.at(-1),超过50毫秒帧数:times.filter(x=>x>50).length,每250毫秒观测峰值:counts});}}requestAnimationFrame(sample);}));
 for(let n=0;n<12;n++){const heap=await cdp.send('Runtime.getHeapUsage');const state=await page.evaluate(()=>(window as any).__farwind());rows.push({采样:n,世界时间:state.state.time,活跃事件人数:state.defense.enemies.filter((e:any)=>e.hp>0).length,卫兵人数:state.state.defense.guards.filter((g:any)=>!g.dead).length,箭数:state.defense.arrows.length,使用堆字节:heap.usedSize,已分配堆字节:heap.totalSize});await page.waitForTimeout(5000);}
 const measured=await frames;await page.keyboard.press('Escape');await page.waitForFunction(()=>(window as any).__farwind().mode==='pause');const frozen=await page.evaluate(()=>(window as any).__farwind().state.time);await page.locator('#modal,#toast').evaluateAll(nodes=>nodes.forEach(n=>(n as HTMLElement).style.visibility='hidden'));await page.screenshot({path:`${root}/performance.png`});await page.locator('#hud,.resident-tools').evaluateAll(nodes=>nodes.forEach(n=>(n as HTMLElement).style.visibility='hidden'));await page.screenshot({path:`${root}/no-hud.png`});expect(await page.evaluate(()=>(window as any).__farwind().state.time)).toBe(frozen);
 expect(rows.some(r=>r.活跃事件人数>0)).toBe(true);await writeFile(`${root}/performance.json`,JSON.stringify({说明:'合并后的冻结生产构建，1280×720、DPR1、Metal、可见浏览器及录像，正常速率60秒，前三怪事件与之后归岗恢复同一页面；250毫秒只读实体观测、5秒堆采样，包含观测开销。仅短测，不是长时内存趋势或稳定60FPS验收。截图通过真实暂停固定同一时间和镜头，清除HUD与居民笔记仅改显示。未修改运行生命或位置。',系统:`${platform()} ${release()}`,处理器:cpus()[0].model,浏览器:browser.version(),画面尺寸:'1280×720',截图世界时间:frozen,...measured,采样:rows},null,2));
});
