import {describe,it,expect} from 'vitest';
import {initialState,parseSave} from '../src/game/systems/state';
import {WindGiftCombat,type GiftTarget} from '../src/game/systems/windGiftCombat';
import {RuneCombat,type RuneEvent} from '../src/game/systems/runeCombat';
import {WIND_GIFTS,EXTRA_WIND_GIFTS,GIFT_RESONANCES,giftCappedValue,giftEffect,resonanceLevel,offerWindGift,type WindGiftId} from '../src/game/systems/windGifts';
import {playerVitals,journeyProgress,JOURNEY_UNITS_PER_METER} from '../src/game/systems/journeyTraining';
import {STRIKES,CombatController,PARRY,type Attack} from '../src/game/systems/combat';
import {SWORD_WIND,resolveSwordWindConfig} from '../src/data/swordWind';
import {SwordWindSystem,type WindMotion} from '../src/game/systems/swordWind';

function arena(ids:WindGiftId[]=[],level=1){
 const state=initialState();state.player.x=0;state.player.y=0;state.skills.swordWindStage=2;state.windGifts.held=ids.map(id=>({id,level}));
 const enemies:GiftTarget[]=[{id:'前排',kind:'enemy',type:'slime',x:100,y:0,hp:10000},{id:'后排',kind:'enemy',type:'archer',x:160,y:0,hp:10000}];
 let now=0,active=true,following=false,serial=0;const hits:RuneEvent[]=[],controls:number[]=[];const companion={hp:300,maxHp:640,point:{x:0,y:0},heal:(a:number)=>{companion.hp=Math.min(companion.maxHp,companion.hp+a);}};
 const engine=new RuneCombat({state:()=>state,targets:()=>enemies,A:()=>100,clear:()=>true,visible:()=>true,blocker:()=>null,push:()=> 'immune',sound:()=>{},checkpoint:()=>{},damage:(e,ev)=>{hits.push(ev);const amount=Math.min(e.hp,ev.amount);e.hp-=amount;return {applied:true,damage:amount,killed:e.hp===0};}});engine.random=()=>1;
 const gifts=new WindGiftCombat(engine,{active:()=>active&&state.player.hp>0,now:()=>now,following:()=>following,companion:()=>following?companion:undefined,move:(e,dx,dy)=>{e.x+=dx;e.y+=dy;return Math.hypot(dx,dy);},stagger:(_e,ms)=>{controls.push(ms);}});
 const motions=():WindMotion[]=>enemies.map(target=>({target,previous:{...target},current:{...target}}));
 const time=(n:number)=>{now=n;state.runes.clock=n;};
 const begin=(wind=false,stage=1,comboId?:number)=>{const a:Attack={id:++serial,comboId,kind:wind?'swordWind':'melee',stage,start:now,facing:3,hit:new Set(),aim:{x:1,y:0},config:{...(wind?SWORD_WIND.strike:STRIKES[stage-1]!)},swordWind:wind?resolveSwordWindConfig(2):undefined};gifts.capture(a,3);return a;};
 const land=(a:Attack,e=enemies[0]!)=>{const bonus=gifts.bonus(a,e),ev=engine.native(`attack:${a.id}`,e,100,a.stage,a.kind==='swordWind',a.stage===3,'out',bonus);gifts.landed(a,e,ev);return bonus;};
 return {state,enemies,gifts,engine,hits,controls,companion,motions,time,begin,land,follow:()=>{following=true;},inactive:()=>{active=false;},advance:(n:number)=>{const prev=now;time(n);gifts.advance(prev,n,motions());}};
}
describe('新风赐完整目录、成长与旧存档兼容',()=>{
 it('范围余震只在真实中心播放一次，多个受击目标仍各自结算伤害',()=>{const a=arena(['aftershock']),parent=a.engine.parent('','wind_gift',{x:100,y:0});expect(a.gifts.area({x:100,y:0},100,parent,.2,'aftershock')).toBe(40);expect(a.hits).toHaveLength(2);expect(a.enemies.map(e=>e.hp)).toEqual([9980,9980]);expect(a.engine.effects.filter(f=>f.visual==='gift:aftershock')).toHaveLength(1);});
 it('美术只消费成立的命中，回血为零、取消I均不伪造特效',()=>{const a=arena(['drinkDew','echoWind','pierceCurtain']);a.begin(true);expect(a.engine.effects.some(f=>f.visual==='gift:echoWind')).toBe(false);a.land(a.begin());expect(a.engine.effects.some(f=>f.visual==='gift:drinkDew')).toBe(false);a.state.player.hp=50;a.advance(601);a.land(a.begin());expect(a.engine.effects.some(f=>f.visual==='gift:drinkDew')).toBe(true);});
 it('专属护盾与减速标记随实际状态到期与清场，不写入存档',()=>{const a=arena(['firstVeil','holdWind']);a.gifts.incoming(10);a.land(a.begin(true));expect(a.gifts.statusVisuals().map(s=>s.id)).toEqual(['firstVeil','holdWind']);a.advance(1501);expect(a.gifts.statusVisuals().map(s=>s.id)).toEqual(['firstVeil']);a.gifts.clear();expect(a.gifts.statusVisuals()).toEqual([]);expect(a.state.windGifts).not.toHaveProperty('visuals');});
 it('六十一种均有中文效果，四十八种新增、十八组共鸣；读档保留旧候选及凭据',()=>{
  expect(Object.keys(WIND_GIFTS)).toHaveLength(61);expect(Object.keys(EXTRA_WIND_GIFTS)).toHaveLength(48);expect(Object.keys(GIFT_RESONANCES)).toHaveLength(18);
  const s=initialState();s.windGifts.held=(Object.keys(WIND_GIFTS) as WindGiftId[]).map(id=>({id,level:4}));s.windGifts.receipts=['旧凭据'];s.windGifts.pending=[{receipt:'旧凭据',candidates:['blade','spring','armor']}];
  const saved=parseSave(JSON.stringify(s));expect(saved.windGifts).toEqual(s.windGifts);
  for(const id of Object.keys(WIND_GIFTS) as WindGiftId[])expect(giftEffect(id,4)).not.toMatch(/undefined|NaN|\{v\}/);
  for(const id of Object.keys(GIFT_RESONANCES) as (keyof typeof GIFT_RESONANCES)[])expect(resonanceLevel(saved.windGifts,id)).toBe(4);
 });
 it('I未解锁不出现依赖I的候选，原候选不会重新抽取',()=>{for(let seed=0;seed<100;seed++){const s=initialState().windGifts;offerWindGift(s,String(seed),seed,false);for(const id of s.pending[0]!.candidates)expect(['gale','blackHole','echoWind','longEdge','holdWind','duality']).not.toContain(id);const prior=structuredClone(s);expect(offerWindGift(s,String(seed),seed,true)).toBe(false);expect(s).toEqual(prior);}});
 it('生命体力叠加不改变里程奖励门槛，旧接口仍有效',()=>{const a=arena(['windBone','longBreath'],4);expect(playerVitals(a.state)).toEqual({maxHp:140,maxStamina:140});expect(journeyProgress(a.state).staminaRemaining).toBe(500);a.state.physique.runDistance=500*JOURNEY_UNITS_PER_METER;expect(journeyProgress(a.state).staminaRemaining).toBe(525);expect(playerVitals({physique:{runDistance:0}})).toEqual({maxHp:100,maxStamina:100});});
 it('明确的几何、时间和减伤上限在高等级仍有效',()=>{const a=arena(['longEdge','broadWind','catchEdge','clearMirror','windRhythm','guardStance','softenWound','guardedBreath','unyielding','holdWind','returningTide'],100);for(const [id,cap] of [['longEdge',.5],['broadWind',.5],['catchEdge',200],['clearMirror',35],['windRhythm',60]] as [WindGiftId,number][])expect(giftCappedValue(a.state.windGifts,id)).toBe(cap);a.state.player.hp=20;expect(a.gifts.incoming(30,a.begin(false,2))).toBeCloseTo(.4);});
});
describe('被动、I贯通与节奏',()=>{
 it('盈风与同心依赖生命和实际同行，净路只强化远程支援',()=>{const a=arena(['fullWind','sharedHeart','clearPath']);const i=a.begin(true);expect(a.gifts.bonus(i,a.enemies[0]!)).toBe(.1);expect(a.gifts.bonus(i,a.enemies[1]!)).toBeCloseTo(.3);a.follow();expect(a.gifts.bonus(i,a.enemies[0]!)).toBeCloseTo(.18);a.state.player.hp=79;expect(a.gifts.bonus(i,a.enemies[0]!)).toBe(.08);a.enemies[1]!.type='bell';expect(a.gifts.bonus(i,a.enemies[1]!)).toBeCloseTo(.28);});
 it('穿帘按不同目标计数，未解锁双穿不加成；贯穿结束才触发一线破军一次',()=>{const a=arena(['pierceCurtain','gale']);const i=a.begin(true);expect(a.land(i)).toBe(0);expect(a.land(i,a.enemies[1]!)).toBe(.15);const wind=new SwordWindSystem().launch(i,a.state.player,0,100)!;a.gifts.finish(wind);a.gifts.finish(wind);expect(a.hits).toHaveLength(1);expect(a.hits[0]!.amount).toBe(50);a.state.skills.swordWindStage=1;const next=a.begin(true);a.land(next);expect(a.gifts.bonus(next,a.enemies[1]!)).toBe(0);});
 it('风律仅每第三次连续施放缩短恢复，超过一秒重置；凝风起手快照',()=>{const a=arena(['windRhythm','stillWind'],2);const first=a.begin(true);expect(a.gifts.bonus(first,a.enemies[0]!)).toBe(.7);a.time(500);a.begin(true);a.time(1000);const third=a.begin(true);expect(third.config!.recovery).toBe(SWORD_WIND.strike.recovery-60);expect(a.gifts.bonus(third,a.enemies[0]!)).toBe(0);a.time(2200);const reset=a.begin(true);expect(reset.config!.recovery).toBe(SWORD_WIND.strike.recovery);expect(a.gifts.bonus(reset,a.enemies[0]!)).toBe(.7);});
 it('聚焦第三击增强并重置，不把同一次回返算新施放；游锋有时限',()=>{const a=arena(['focusWind','roamEdge']);for(let k=0;k<2;k++){a.time(k*400);a.land(a.begin(true));}a.time(800);const third=a.begin(true);expect(a.land(third)).toBe(.25);a.land({...third,windLeg:'back'});a.time(1200);expect(a.land(a.begin(true))).toBe(0);expect(a.gifts.speed()).toBe(.1);a.time(2201);expect(a.gifts.speed()).toBe(0);});
 it('每第四次I只发一次多向回声，160毫秒延迟，派生不会递归触发；风声不绝下一次I消费',()=>{const a=arena(['echoWind','windRhythm']);let i:Attack|undefined;for(let k=0;k<4;k++){a.time(k*300);i=a.begin(true);if(k<3)a.gifts.release(new SwordWindSystem().launch(i,a.state.player,k*300,100)!);}i!.swordWind=resolveSwordWindConfig(5);const wind=new SwordWindSystem().launch(i!,a.state.player,900,100)!;a.gifts.release(wind);a.gifts.release(wind);a.advance(1059);expect(a.gifts.metrics.echoes).toBe(0);a.advance(1060);expect(a.gifts.metrics.echoes).toBe(1);a.advance(1500);expect(a.hits.length).toBeGreaterThan(0);expect(a.hits.every(h=>h.sourceKind!=='native'&&h.amount===35)).toBe(true);expect(a.gifts.bonus(a.begin(true),a.enemies[0]!)).toBe(.25);expect(a.gifts.bonus(a.begin(true),a.enemies[0]!)).toBe(0);});
 it('静风破云标记不会被同次I或回返消费',()=>{const a=arena(['stillWind','focusWind']);const i=a.begin(true);a.land(i);a.land({...i,windLeg:'back'});expect(a.hits).toHaveLength(0);a.time(300);a.land(a.begin());expect(a.hits).toHaveLength(1);expect(a.hits[0]!.amount).toBe(40);});
});
describe('J连段、终结与混合',()=>{
 it('连锋沉锋按段位加成，开隙只被后续命中消费；踏锋起手即消费',()=>{const a=arena(['chainedEdge','heavyEdge','openGap','stepEdge']);a.gifts.startDash(180);expect(a.gifts.bonus(a.begin(),a.enemies[0]!)).toBe(.2);expect(a.gifts.bonus(a.begin(),a.enemies[0]!)).toBe(0);const last=a.begin(false,3);expect(a.land(last)).toBeCloseTo(.35);const next=a.begin();expect(a.land(next)).toBe(.25);expect(a.gifts.bonus(a.begin(),a.enemies[0]!)).toBe(0);});
 it('余震延迟位置固定，山鸣破阵扩大半径并追加伤害；最多五敌',()=>{const a=arena(['aftershock','shock','heavyEdge']);a.enemies.push(...Array.from({length:8},(_,i)=>({id:`远敌${i}`,kind:'enemy',hp:10000,x:210,y:i})));a.land(a.begin(false,3));a.advance(299);expect(a.hits).toHaveLength(0);a.advance(300);expect(a.hits).toHaveLength(5);expect(a.hits.every(h=>h.amount===65)).toBe(true);});
 it('终息按攻击门禁返体力，息锋循环只持续两秒',()=>{const a=arena(['finalBreath','breath']);a.state.player.stamina=50;const j=a.begin(false,3);a.land(j);a.land(j,a.enemies[1]!);expect(a.state.player.stamina).toBe(54);expect(a.gifts.regen()).toBe(.15);a.time(2000);expect(a.gifts.regen()).toBe(0);});
 it('百斩成锋要求同一连段一二段实际命中，终结只追加一次',()=>{const a=arena(['blade','chainedEdge','catchEdge']);a.land(a.begin(false,1,9));a.land(a.begin(false,2,9));const final=a.begin(false,3,9);a.land(final);a.land(final,a.enemies[1]!);expect(a.hits).toHaveLength(1);expect(a.hits[0]!.amount).toBe(40);const b=arena(['blade','chainedEdge','catchEdge']);b.land(b.begin(false,1,1));b.land(b.begin(false,2,2));b.land(b.begin(false,3,3));expect(b.hits).toHaveLength(0);});
 it('双奏与轮息需同目标两秒交替，蓄转起手消费、引刃只强化J第一段',()=>{const a=arena(['duet','cyclicBreath','storedTurn','guidingEdge']);a.state.player.stamina=50;a.land(a.begin(false,3));a.time(300);const i=a.begin(true);expect(a.land(i)).toBeCloseTo(.55);expect(a.state.player.stamina).toBe(53);expect(a.gifts.bonus(a.begin(false,2),a.enemies[0]!)).toBe(.2);expect(a.land(a.begin(false,1))).toBeCloseTo(.45);expect(a.gifts.bonus(a.begin(true),a.enemies[1]!)).toBe(0);});
 it('两仪及两仪流转需同目标三次交替，实际冲击才恢复体力和护盾',()=>{const a=arena(['duality','cyclicBreath']);a.state.player.stamina=30;a.land(a.begin());a.time(300);a.land(a.begin(true));a.time(600);a.land(a.begin());expect(a.hits).toHaveLength(2);expect(a.hits.every(h=>h.amount===60)).toBe(true);expect(a.state.player.stamina).toBe(36);expect(a.gifts.snapshot().shield).toBe(3);});
 it('风刃轮舞需终结I近战，而普通J/I/J不满足终结条件',()=>{const a=arena(['duet','storedTurn','guidingEdge']);a.land(a.begin(false,3));a.time(400);a.land(a.begin(true));a.time(800);a.land(a.begin());expect(a.hits.length).toBeGreaterThan(0);expect(a.hits.every(h=>h.amount===50)).toBe(true);const b=arena(['duet','storedTurn','guidingEdge']);b.land(b.begin());b.land(b.begin(true));b.land(b.begin());expect(b.hits).toHaveLength(0);});
 it('接刃延长的是动作结束后的接续，不提前打断攻击；明镜扩展精准边界',()=>{const c=new CombatController();c.parryPrecisionBonus=35;c.parry={id:1,start:0,facing:3,actionUntil:500};expect(c.parryQuality(PARRY.precise+34)).toBe('perfect');expect(c.parryQuality(PARRY.precise+35)).toBe('normal');expect(c.nextBoundary(90,200)).toBe(125);});
});
describe('防御、治疗与弹反',()=>{
 it('初幕首次受击有效，护盾重复取大并总量封顶；风甲成幕仅被敌人击破时触发',()=>{const a=arena(['firstVeil','armor']);a.enemies[0]!.x=50;expect(a.gifts.incoming(10)).toBe(1);expect(a.gifts.snapshot().shield).toBe(8);expect(a.gifts.absorb(5)).toBe(0);expect(a.gifts.absorb(5)).toBe(2);expect(a.hits).toHaveLength(1);expect(a.hits.every(h=>h.amount===30)).toBe(true);a.gifts.incoming(10);expect(a.gifts.snapshot().shield).toBe(0);a.gifts.grantShield(500,2000);a.gifts.grantShield(5,1000);expect(a.gifts.snapshot().shield).toBe(20);a.time(2000);expect(a.gifts.absorb(5)).toBe(5);});
 it('护息、不屈和缓创依赖实际阈值且缓创有冷却',()=>{const a=arena(['softenWound','guardedBreath','unyielding']);expect(a.gifts.incoming(19)).toBeCloseTo(.92);expect(a.gifts.incoming(20)).toBeCloseTo(.72);expect(a.gifts.incoming(20)).toBeCloseTo(.92);a.state.player.hp=30;a.state.player.stamina=40;expect(a.gifts.incoming(20)).toBeCloseTo(.88);a.time(8000);expect(a.gifts.incoming(20)).toBeCloseTo(.68);});
 it('断势仅精准弹反且遵守首领机关免疫，借风反击不消费、普通I起手消费',()=>{const a=arena(['breakStance','borrowWind']);a.gifts.parry(false,a.enemies[0]);expect(a.controls).toHaveLength(0);a.gifts.parry(true,a.enemies[0]);expect(a.controls).toEqual([100]);a.enemies[1]!.boss='首领';a.gifts.parry(true,a.enemies[1]);expect(a.controls).toHaveLength(1);const counter={...a.begin(),id:900,kind:'counter' as const,counter:'perfect' as const};a.gifts.capture(counter);expect(a.gifts.bonus(counter,a.enemies[0]!)).toBe(0);expect(a.gifts.bonus(a.begin(true),a.enemies[0]!)).toBe(.3);expect(a.gifts.bonus(a.begin(true),a.enemies[0]!)).toBe(0);});
 it('精准借风还刃追加延迟回声，普通弹反没有额外回声',()=>{const a=arena(['borrowWind','clearMirror']);a.gifts.parry(true);const i=a.begin(true),wind=new SwordWindSystem().launch(i,a.state.player,0,100)!;a.gifts.release(wind);a.advance(160);a.advance(500);expect(a.hits.length).toBeGreaterThan(0);expect(a.hits.every(h=>h.amount===40)).toBe(true);const b=arena(['borrowWind','clearMirror']);b.gifts.parry(false);const j=b.begin(true);b.gifts.release(new SwordWindSystem().launch(j,b.state.player,0,100)!);b.advance(500);expect(b.hits).toHaveLength(0);});
 it('回锋成阵强化既有释放剑气，普通弹反保留原数值',()=>{const a=arena(['riposte','breakStance']);a.engine.armGiftRiposte(true);a.engine.captureGiftAttack('精准',false);a.engine.releaseGiftAttack('精准',a.state.player,{x:1,y:0});expect(a.hits.every(h=>h.amount===70)).toBe(true);expect(a.hits.length).toBeGreaterThan(0);});
 it('饮露、止血和滴露成泉受真实伤害及每秒5%治疗总上限约束',()=>{const a=arena(['drinkDew','stopBleeding'],10);a.state.player.hp=40;a.gifts.hurt(0);a.advance(1000);expect(a.state.player.hp).toBe(40);a.gifts.hurt(20);a.land(a.begin());expect(a.state.player.hp).toBe(45);a.advance(1999);expect(a.state.player.hp).toBe(45);a.advance(2000);expect(a.state.player.hp).toBeGreaterThan(45);expect(a.state.player.hp).toBeLessThanOrEqual(50);a.advance(5001);const hp=a.state.player.hp;a.advance(7000);expect(a.state.player.hp).toBe(hp);});
 it('止血按模拟秒积分，暂停和同刻检查不多治疗',()=>{const run=(step:number)=>{const a=arena(['stopBleeding']);a.state.player.hp=50;a.gifts.hurt(10);for(let n=step;n<=4000;n+=step){a.advance(n);a.gifts.advance(n,n,a.motions());}return a.state.player.hp;};expect(run(10)).toBeCloseTo(54,7);expect(run(100)).toBeCloseTo(run(10),7);});
 it('余泽及春泉余泽仅使用真实溢出量，不计算药剂整份治疗',()=>{const a=arena(['lingeringGrace','spring']);a.gifts.potionOverflow(10);expect(a.gifts.snapshot().shield).toBe(5);a.state.player.hp=98;a.gifts.encounterHeal(6);expect(a.state.player.hp).toBe(100);expect(a.gifts.snapshot().shield).toBe(5);a.time(20001);a.gifts.encounterHeal(6);expect(a.gifts.snapshot().shield).toBe(3);a.time(60002);expect(a.gifts.snapshot().shield).toBe(0);});
});
describe('风步、控场与伙伴',()=>{
 it('掠影必须收到实际躲避事件，强化起手消费；踏影追刃只发一次剑气',()=>{const a=arena(['skimShadow','stepEdge']);expect(a.gifts.bonus(a.begin(),a.enemies[0]!)).toBe(0);a.gifts.startDash(180);a.gifts.dodged();const j=a.begin();expect(a.land(j)).toBeCloseTo(.45);a.land(j,a.enemies[1]!);expect(a.hits.every(h=>h.amount===30)).toBe(true);expect(a.hits).toHaveLength(2);expect(a.gifts.bonus(a.begin(),a.enemies[0]!)).toBe(0);});
 it('残风沿真实移动路径扫掠，每次每敌一次、最多五敌；回潮与残风成潮落地后生效',()=>{const a=arena(['residualWind','returningTide']);a.gifts.startDash(200);a.state.player.x=120;a.advance(100);expect(a.hits).toHaveLength(1);a.state.player.x=180;a.advance(200);expect(a.hits).toHaveLength(2);expect(a.hits.every(h=>h.amount===20)).toBe(true);a.advance(499);expect(a.hits).toHaveLength(2);a.advance(500);expect(a.hits.some(h=>h.amount===25)).toBe(true);expect(a.gifts.slow(a.enemies[1]!)).toBe(.25);a.advance(2201);expect(a.gifts.slow(a.enemies[1]!)).toBe(0);});
 it('脱围需要起点三个近敌，只在落地后加速；新增移速合计上限40%',()=>{const a=arena(['escapeCircle','roamEdge'],100);a.enemies.push({id:'第三敌',kind:'enemy',x:50,y:0,hp:10000});a.enemies[1]!.x=130;a.gifts.startDash(200);expect(a.gifts.speed()).toBe(0);a.advance(200);expect(a.gifts.speed()).toBe(.25);a.land(a.begin(true));expect(a.gifts.speed()).toBe(.4);a.time(2201);expect(a.gifts.speed()).toBe(0);});
 it('定风、迟锋与定风围猎只对实际减速和成功牵引生效；机关首领不位移',()=>{const a=arena(['holdWind','curledWind','delayedEdge']);a.enemies[0]!.x=0;a.enemies[1]!.x=60;a.land(a.begin(true),a.enemies[1]!);for(let n=0;n<3;n++){a.time(n*200);a.land(a.begin(true));}expect(a.hits.some(h=>h.amount===30)).toBe(true);expect(a.gifts.metrics.pulled).toBe(20);expect(a.gifts.bonus(a.begin(),a.enemies[0]!)).toBe(.15);const b=arena(['holdWind','curledWind','delayedEdge'],10);b.enemies[0]!.boss='首领';b.enemies[1]!.passiveRoot=true;for(let n=0;n<3;n++)b.land(b.begin(true));expect(b.gifts.slow(b.enemies[0]!)).toBe(.2);expect(b.gifts.metrics.pulled).toBe(0);expect(b.hits).toHaveLength(0);});
 it('压阵终结控场有冷却与免疫上限',()=>{const a=arena(['suppressField'],10);a.land(a.begin(false,3));expect(a.controls).toEqual([200]);a.land(a.begin(false,3));expect(a.controls).toHaveLength(1);a.time(2000);a.enemies[0]!.boss='首领';a.land(a.begin(false,3));expect(a.controls).toHaveLength(1);});
 it('护伴只保护实际被敌人攻击的小宝；归息、并肩、递锋同行来自真实伙伴命中',()=>{const a=arena(['protectCompanion','returningBreath','relayEdge','sideBySide']);a.follow();a.state.player.stamina=50;a.enemies[0]!.targetId='xiaobao';a.enemies[0]!.attack={};a.land(a.begin());expect(a.gifts.snapshot().companionShield).toBe(32);expect(a.gifts.companionBonus(a.enemies[0]!)).toBe(.2);a.gifts.companionLanded(a.enemies[0]!);expect(a.state.player.stamina).toBe(52);expect(a.companion.hp).toBeCloseTo(306.4);expect(a.gifts.companionBonus(a.enemies[0]!)).toBe(0);expect(a.land(a.begin())).toBe(.15);expect(a.hits.some(h=>h.amount===30)).toBe(true);expect(a.gifts.absorbCompanion(40)).toBe(8);});
 it('没有实际同行伙伴时护伴不授盾，递锋标记到期不影响伙伴',()=>{const a=arena(['protectCompanion','relayEdge']);a.enemies[0]!.targetId='xiaobao';a.enemies[0]!.attack={};a.land(a.begin());expect(a.gifts.snapshot().companionShield).toBe(0);a.time(3000);expect(a.gifts.companionBonus(a.enemies[0]!)).toBe(0);});
});
describe('生命周期与递归边界',()=>{
 it('护伴使用受击前的攻击意图：J打断正在攻击小宝的敌人后仍授盾',()=>{const a=arena(['protectCompanion']);a.follow();const target=a.enemies[0]!;target.targetId='xiaobao';target.attack={cancelled:false,activeUntil:1000};const j=a.begin();a.gifts.bonus(j,target);target.attack.cancelled=true;a.gifts.landed(j,target,a.engine.native(`attack:${j.id}`,target,100,1));expect(a.gifts.snapshot().companionShield).toBe(32);});
 it('被打断的I起手不增加追鸣释放次数，第四次真正释放才产生回声',()=>{const a=arena(['echoWind']);for(let n=0;n<3;n++)a.begin(true);for(let n=0;n<4;n++){a.time(n*500);const i=a.begin(true);a.gifts.release(new SwordWindSystem().launch(i,a.state.player,n*500,100)!);a.advance(n*500+200);expect(a.gifts.metrics.echoes).toBe(n===3?1:0);}});
 it('出程只击中一敌，回程撞到另一敌也不视为贯穿两敌',()=>{const a=arena(['gale','pierceCurtain']);const i=a.begin(true);a.land(i);a.land({...i,windLeg:'back'},a.enemies[1]!);a.gifts.finish(new SwordWindSystem().launch(i,a.state.player,0,100)!);expect(a.hits).toHaveLength(0);});
 it('护伴不把已取消或已结束的敌方动作视为正在攻击小宝',()=>{const a=arena(['protectCompanion']);a.follow();a.enemies[0]!.targetId='xiaobao';a.enemies[0]!.attack={cancelled:true};a.land(a.begin());expect(a.gifts.snapshot().companionShield).toBe(0);a.enemies[0]!.attack={activeUntil:0};a.land(a.begin());expect(a.gifts.snapshot().companionShield).toBe(0);});
 it('训练、死亡、换场时清除回声、领域、治疗、护盾和所有临时加成',()=>{const a=arena(['aftershock','stopBleeding','firstVeil','stepEdge']);a.land(a.begin(false,3));a.gifts.hurt(10);a.gifts.incoming(10);a.gifts.startDash(200);expect(a.gifts.busy).toBe(true);a.inactive();a.advance(1000);expect(a.gifts.busy).toBe(false);expect(a.gifts.snapshot().shield).toBe(0);expect(a.hits).toHaveLength(0);const attack=a.begin();expect(a.gifts.bonus(attack,a.enemies[0]!)).toBe(0);});
 it('派生事件及训练木桩不触发新原生风赐，不扩散新的连锁',()=>{const a=arena(['duality','aftershock','drinkDew','holdWind','relayEdge']);a.state.player.hp=50;const j=a.begin(false,3),parent=a.engine.parent('','wind_gift',a.enemies[0]!);a.gifts.landed(j,a.enemies[0]!,parent);a.enemies[1]!.kind='trainingDummy';a.land(j,a.enemies[1]!);a.advance(1000);expect(a.hits).toHaveLength(0);expect(a.state.player.hp).toBe(50);expect(a.gifts.slow(a.enemies[1]!)).toBe(0);});
 it('等级快照不受攻击过程中升级影响，共鸣取最低组件等级',()=>{const a=arena(['chainedEdge','heavyEdge']);const j=a.begin(false,3);a.state.windGifts.held.forEach(g=>g.level=8);expect(a.gifts.bonus(j,a.enemies[0]!)).toBeCloseTo(.35);const b=arena(['gale','pierceCurtain'],3);b.state.windGifts.held[1]!.level=1;expect(resonanceLevel(b.state.windGifts,'oneLineArmy')).toBe(1);});
});
