import {describe,it,expect} from 'vitest';
import {initialState,validate} from '../src/game/systems/state';
import {initialRunes,runeSnapshot} from '../src/game/systems/runeState';
import {legacySnapshot,legacyObjective,legacyRewardSafe} from '../src/game/systems/windLegacy';
import {LEGACY_SITES,LEGACY_ENCOUNTERS} from '../src/data/windLegacy';
import {props,solidPropAt,syncMapGeometry} from '../src/data/world';
import {motionBlocked} from '../src/game/systems/obstacles';
import {settleEncounterDeath} from '../src/game/systems/encounterState';
import {RuneCombat,type RuneTarget,type RuneEvent} from '../src/game/systems/runeCombat';
import {WindAim} from '../src/game/systems/windAim';
import {resolveSwordWindConfig} from '../src/data/swordWind';
import {combatVisual} from '../src/data/animation';
const safe={combat:false,boss:false,defense:false,trial:false,story:false,action:false};
function clear(s:ReturnType<typeof initialState>,id:string){s.encounters.groups[id].activated=true;for(const u of s.encounters.groups[id].members){if(s.encounters.groups[id].boss&&u.id.startsWith('boss-'))s.encounters.groups[id].boss!.stage='battle';settleEncounterDeath(s.encounters,u.id,false);}}
function harness(mode:'focus'|'weave'|'break'|'ring'){
 const s=initialState();s.player.x=0;s.player.y=0;const id=mode==='focus'||mode==='weave'?'r32':'r12';s.runes.owned=[id];s.runes.slots[0]=id;s.runes.growth[id]={advanced:true,branch:mode};const enemies:RuneTarget[]=[{id:'目标甲',x:50,y:0,hp:10000}],events:RuneEvent[]=[];
 const c=new RuneCombat({state:()=>s,targets:()=>enemies,A:()=>100,visible:()=>true,clear:()=>true,blocker:()=>null,damage:(e,ev)=>{events.push(ev);e.hp-=ev.amount;return {applied:true,damage:ev.amount,killed:false};},push:()=> 'moved',sound:()=>{},checkpoint:()=>{}});c.random=()=>1;
 const trace=(id:number,x:number,root='旧风')=>{const p=c.parent('r32','wind_hit',{x,y:0});c.traces.push({id,point:{x,y:0},until:4000,root,parent:p});};
 const wind={attack:{kind:'swordWind'},config:{width:20},rootActionId:2,leg:'back',previous:{x:0,y:0},position:{x:65,y:0},terminated:false} as any;
 return {s,c,enemies,events,trace,wind};
}
describe('散落风式最小闭环',()=>{
 it('领奖对话本身不阻止授予选择权，其余安全锁仍拒绝，选择分支照常拒绝剧情锁',()=>{expect(legacyRewardSafe({...safe,story:true})).toBe(true);for(const k of ['combat','boss','defense','trial','action'] as const)expect(legacyRewardSafe({...safe,story:true,[k]:true})).toBe(false);const s=initialState();s.runes.owned=['r12'];s.runes.growth.r12={advanced:true,branch:null};expect(()=>runeSnapshot(s,{kind:'branch',id:'r12',branch:'ring'},{...safe,story:true})).toThrow('剧情');});
 it('旧第16版无损补任务和两枚成长，不发奖、不重置首领或分支',()=>{const s=initialState();s.runes.growth.r31={advanced:true,branch:'anchor'};s.runes.owned=['r31'];const old:any=structuredClone(s);old.schema_version=16;delete old.windLegacy;old.runes.version=2;delete old.runes.growth.r32;delete old.runes.growth.r12;for(const d of LEGACY_ENCOUNTERS)delete old.encounters.groups[d.id];const next=validate(old);expect(next.windLegacy.wind).toBe(0);expect(next.runes.growth.r32).toEqual({advanced:false,branch:null});expect(next.runes.growth.r31).toEqual(s.runes.growth.r31);expect(next.encounters.groups['east-thorn-camp']).toEqual(s.encounters.groups['east-thorn-camp']);});
 it('预设分支一并恢复、旧预设保留当前分支与冷却、不授予解锁',()=>{let s=initialState();s.runes.owned=['r31','r32'];s.runes.slots[0]='r31';s.runes.slots[1]='r32';s.runes.growth.r31={advanced:true,branch:'anchor'};s.runes.growth.r32={advanced:true,branch:'weave'};s.runes.cooldowns.r31=1200;s=runeSnapshot(s,{kind:'preset-save',index:0},safe);s.runes.growth.r31.branch='path';s.runes.growth.r32.branch='focus';s=runeSnapshot(s,{kind:'preset-load',index:0},safe);expect(s.runes.growth.r31.branch).toBe('anchor');expect(s.runes.growth.r32.branch).toBe('weave');expect(s.runes.cooldowns.r31).toBe(1200);delete s.runes.presets[0].branches;s.runes.growth.r32.branch='focus';expect(runeSnapshot(s,{kind:'preset-load',index:0},safe).runes.growth.r32.branch).toBe('focus');s.runes.growth.r32={advanced:false,branch:null};s.runes.presets[0].branches={r32:'weave'};expect(runeSnapshot(s,{kind:'preset-load',index:0},safe).runes.growth.r32.advanced).toBe(false);});
 it('新交互点与固定敌人都有合法站位，入口到目标有明确位置',()=>{const s=initialState();syncMapGeometry(false,[],[],s.windLegacy);for(const d of LEGACY_ENCOUNTERS)for(const m of d.members)expect(motionBlocked(m.x,m.y),m.id).toBe(false);expect(Object.entries(LEGACY_SITES).filter(([key,p])=>motionBlocked(p.x,p.y+65)).map(([key,p])=>({位置:key,障碍:props.filter(o=>o.solid&&Math.abs(o.x-p.x)<o.solid[0]/2+12&&p.y+65>o.y-o.solid[1]-10&&p.y+65<o.y+10).map(o=>o.id)}))).toEqual([]);expect(legacyObjective(s,'wind').point).toBeTruthy();});
 it('一条三节点支线与已清旧据点收尾可保存、重复领奖拒绝，另一条仍独立',()=>{let s=initialState();s.skills.swordWindStage=1;s.skills.completedLessons=['windLessonResolved'];s.skills.discoveredLessons=['windLessonResolved'];const book=props.find(p=>p.id==='lesson-windLessonResolved')!,guide=props.find(p=>p.id==='training-guide')!;s.player={...s.player,x:book.x,y:book.y+60};s=legacySnapshot(s,'accept-wind',true);s.player.x=LEGACY_SITES.windRecord.x;s.player.y=LEGACY_SITES.windRecord.y+60;s=legacySnapshot(s,'read-wind',true);s.windLegacy.device=true;clear(s,'legacy-wind-device');s.player.x=guide.x;s.player.y=guide.y+60;expect(()=>legacySnapshot(s,'reward-wind',false)).toThrow('安全');s=legacySnapshot(s,'reward-wind',true);expect(s.runes.growth.r32.advanced).toBe(true);clear(s,'legacy-wind-passage');s.player.x=LEGACY_SITES.windExit.x;s.player.y=LEGACY_SITES.windExit.y+60;s=legacySnapshot(s,'finish-wind',true);clear(s,'east-thorn-camp');s.player.x=LEGACY_SITES.ending.x;s.player.y=LEGACY_SITES.ending.y+60;const before=s.coins;s=legacySnapshot(s,'ending',true);expect(validate(s).mapProgress.shortcuts).toContain('east-corridor');expect(s.coins-before).toBe(36);expect(()=>legacySnapshot(s,'ending',true)).toThrow('已经');expect(s.windLegacy.blade).toBe(0);expect(s.runes.growth.r12.advanced).toBe(false);});
 it('织风最近合法两点原子消费、每目标一次、单点回退、同去程不消费',()=>{const h=harness('weave');h.trace(1,40);h.trace(3,160);h.trace(2,120);h.c.tracePass(h.wind);expect(h.c.traces.map(t=>t.id)).toEqual([3]);expect(h.c.bands[0].end.x).toBe(120);expect(h.events[0].amount).toBe(75);h.c.advance(400);expect(h.events).toHaveLength(1);h.c.advance(501);expect(h.c.bands).toHaveLength(0);const lone=harness('weave');lone.trace(1,40);lone.c.tracePass(lone.wind);expect(lone.events[0].amount).toBe(40);const own=harness('weave');own.trace(1,40,'attack:2');own.wind.leg='out';own.c.tracePass(own.wind);expect(own.c.traces).toHaveLength(1);});
 it('织风遮挡终点与自身去程资格不能绕过，凝痕缩小范围',()=>{const h=harness('weave');h.trace(1,40);h.trace(2,120,'attack:2');h.wind.leg='out';h.c.tracePass(h.wind);expect(h.c.bands).toHaveLength(0);const wall=harness('weave');wall.trace(1,40);wall.trace(2,120);wall.c.ctx.blocker=()=>({t:.5});wall.c.tracePass(wall.wind);expect(wall.c.bands).toHaveLength(0);const focus=harness('focus');focus.enemies.push({id:'外缘',x:85,y:0,hp:10000});focus.trace(1,40);focus.c.tracePass(focus.wind);expect(focus.events.map(e=>e.amount)).toEqual([90]);});
 it('两种破岸只在唯一终结产生，环潮周围命中且遮挡排除，断势窄短',()=>{for(const mode of ['break','ring'] as const){const h=harness(mode);h.enemies.push({id:'后方',x:-50,y:0,hp:10000});const ev=h.c.native('同一终结',h.enemies[0],100,4,false,true);h.c.nativeLanded(h.enemies[0],ev,100);h.c.nativeLanded(h.enemies[1],h.c.native('同一终结',h.enemies[1],100,4,false,true),100);if(mode==='break'){expect(h.c.projectiles).toHaveLength(1);expect(h.c.projectiles[0]).toMatchObject({maxDistance:140,radius:18,damage:110.00000000000001});}else{expect(h.events.filter(e=>e.tags.includes('tide_hit'))).toHaveLength(2);expect(h.c.projectiles).toHaveLength(0);}}
 const h=harness('ring');h.c.ctx.clear=(a,b)=>b.x>0;h.c.finisher(h.enemies[0],h.c.parent('r12','finisher',h.s.player));expect(h.events).toHaveLength(1);});
 it('切换使用合法目标稳定循环，单目标不丢锁，失效回落',()=>{const aim=new WindAim(),config=resolveSwordWindConfig(1),p={x:0,y:0},targets=[{id:'乙',x:130,y:0,hp:100},{id:'甲',x:80,y:0,hp:100}];aim.select(p,config,targets,()=>null);const initial=aim.target;aim.cycle(p,config,targets,()=>null);expect(aim.target).not.toBe(initial);expect(aim.manual).toBe(true);const chosen=aim.target;aim.select(p,config,targets,()=>null);expect(aim.target).toBe(chosen);expect(aim.cycle(p,config,targets.filter(t=>t.id===chosen),()=>null)?.target).toBe(chosen);targets.find(t=>t.id===chosen)!.hp=0;expect(aim.select(p,config,targets,()=>null)?.target).toBe(initial);});
 it('第四刀使用独立三向六姿态纹理与同一战斗时间轴',()=>{for(const f of [0,1,2,3] as const){const v=[0,95,150,210,275,390].map(t=>combatVisual(4,f,t));expect(v.every(v=>v.texture==='hero-melee-finisher')).toBe(true);expect(new Set(v.map(v=>v.frameIndex)).size).toBeGreaterThan(3);expect(v.every(v=>v.provisional)).toBe(true);}});
});
