// 新风赐定义与共鸣共用一份目录，等级只增加明确列出的数值。
export const EXTRA_WIND_GIFTS = {
 windBone: {name:"风骨",group:"被动",value:10,effect:"最大生命增加{v}点",unit:"点",cap:undefined},
 longBreath: {name:"长息",group:"被动",value:10,effect:"最大体力增加{v}点",unit:"点",cap:undefined},
 fullWind: {name:"盈风",group:"被动",value:0.1,effect:"生命至少80%时，原生伤害增加{v}%",unit:"%",cap:undefined},
 longEdge: {name:"长锋",group:"I贯通",value:0.15,effect:"正式I距离增加{v}%（上限50%）",unit:"%",cap:0.5},
 broadWind: {name:"阔风",group:"I贯通",value:0.15,effect:"正式I宽度增加{v}%（上限50%）",unit:"%",cap:0.5},
 pierceCurtain: {name:"穿帘",group:"I贯通",value:0.15,effect:"双穿解锁后，每次I第二个及后续不同目标伤害增加{v}%",unit:"%",cap:undefined},
 clearPath: {name:"净路",group:"I贯通",value:0.2,effect:"原生I对远程和支援敌人伤害增加{v}%",unit:"%",cap:undefined},
 windRhythm: {name:"风律",group:"I节奏",value:30,effect:"每第三次连续I恢复段减少{v}毫秒，间隔超过1秒重置（上限60毫秒）",unit:"毫秒",cap:60},
 echoWind: {name:"追鸣",group:"I节奏",value:0.35,effect:"每第四次I延后160毫秒发出{v}%基础攻击伤害回声",unit:"%",cap:undefined},
 stillWind: {name:"凝风",group:"I节奏",value:0.35,effect:"1.2秒未施放I后，下次原生I伤害增加{v}%",unit:"%",cap:undefined},
 focusWind: {name:"聚焦",group:"I节奏",value:0.25,effect:"2秒内同目标连续I命中的第三击伤害增加{v}%",unit:"%",cap:undefined},
 roamEdge: {name:"游锋",group:"I节奏",value:0.1,effect:"I命中后一秒走速增加{v}%（上限20%）",unit:"%",cap:0.2},
 chainedEdge: {name:"连锋",group:"J连段",value:0.15,effect:"第二段起原生J伤害增加{v}%",unit:"%",cap:undefined},
 catchEdge: {name:"接刃",group:"J连段",value:60,effect:"J连段结束后的衔接窗口增加{v}毫秒（上限200毫秒）",unit:"毫秒",cap:200},
 guardStance: {name:"守势",group:"J连段",value:0.12,effect:"原生J第二段起，攻击期间减伤{v}%（上限25%）",unit:"%",cap:0.25},
 stepEdge: {name:"踏锋",group:"J连段",value:0.2,effect:"风步后三秒内下一次原生J伤害增加{v}%，起手消耗",unit:"%",cap:undefined},
 heavyEdge: {name:"沉锋",group:"J终结",value:0.2,effect:"原生J终结伤害增加{v}%",unit:"%",cap:undefined},
 openGap: {name:"开隙",group:"J终结",value:0.25,effect:"终结命中标记2秒，下次原生命中伤害增加{v}%并消耗",unit:"%",cap:undefined},
 aftershock: {name:"余震",group:"J终结",value:0.4,effect:"终结命中300毫秒后产生{v}%基础伤害冲击，半径90、最多五目标、冷却2秒",unit:"%",cap:undefined},
 finalBreath: {name:"终息",group:"J终结",value:4,effect:"终结实际命中恢复{v}点体力，冷却1秒",unit:"点",cap:undefined},
 firstVeil: {name:"初幕",group:"防御",value:0.08,effect:"受击前获得{v}%最大生命护盾，持续10秒、冷却20秒",unit:"%",cap:undefined},
 softenWound: {name:"缓创",group:"防御",value:0.2,effect:"单次入射伤害至少为最大生命20%时减伤{v}%，冷却8秒（上限40%）",unit:"%",cap:0.4},
 guardedBreath: {name:"护息",group:"防御",value:0.08,effect:"体力至少一半时减伤{v}%（上限20%）",unit:"%",cap:0.2},
 unyielding: {name:"不屈",group:"防御",value:0.12,effect:"生命不超过30%时减伤{v}%（上限30%）",unit:"%",cap:0.3},
 clearMirror: {name:"明镜",group:"弹反",value:15,effect:"精准弹反窗口增加{v}毫秒（上限35毫秒）",unit:"毫秒",cap:35},
 breakStance: {name:"断势",group:"弹反",value:100,effect:"精准弹反额外失衡{v}毫秒，首领与机关免疫（上限200毫秒）",unit:"毫秒",cap:200},
 borrowWind: {name:"借风",group:"弹反",value:0.3,effect:"成功弹反后三秒内下一次原生I伤害增加{v}%，反击不消耗",unit:"%",cap:undefined},
 drinkDew: {name:"饮露",group:"治疗",value:0.01,effect:"原生实际命中恢复{v}%最大生命，冷却600毫秒",unit:"%",cap:undefined},
 stopBleeding: {name:"止血",group:"治疗",value:0.04,effect:"实际生命受损后四秒内恢复{v}%最大生命，冷却10秒",unit:"%",cap:undefined},
 lingeringGrace: {name:"余泽",group:"治疗",value:0.5,effect:"恢复药剂的溢出治疗有{v}%转为20秒护盾",unit:"%",cap:undefined},
 skimShadow: {name:"掠影",group:"风步",value:0.25,effect:"风步无敌帧实际躲过攻击后，三秒内下次原生J或I增伤{v}%，冷却1秒",unit:"%",cap:undefined},
 residualWind: {name:"残风",group:"风步",value:0.2,effect:"真实风步路径造成{v}%基础伤害，每次最多五目标、每目标一次",unit:"%",cap:undefined},
 escapeCircle: {name:"脱围",group:"风步",value:0.15,effect:"风步起点150范围至少三敌，结束后两秒走速增加{v}%，冷却3秒（上限25%）",unit:"%",cap:0.25},
 holdWind: {name:"定风",group:"控场",value:0.15,effect:"原生I命中减速{v}%，持续1.5秒；本项上限30%、首领20%",unit:"%",cap:0.3},
 curledWind: {name:"卷风",group:"控场",value:20,effect:"每第三次I实际命中牵引周围90范围最多五敌{v}距离，冷却2秒（上限40）",unit:"距离",cap:40},
 suppressField: {name:"压阵",group:"控场",value:120,effect:"原生J终结额外失衡{v}毫秒，冷却2秒；首领与机关免疫（上限200毫秒）",unit:"毫秒",cap:200},
 returningTide: {name:"回潮",group:"控场",value:0.25,effect:"风步落地留下60半径、两秒的{v}%减速区域，冷却3秒（上限40%）",unit:"%",cap:0.4},
 delayedEdge: {name:"迟锋",group:"控场",value:0.15,effect:"对被风赐减速的敌人，原生伤害增加{v}%",unit:"%",cap:undefined},
 sharedHeart: {name:"同心",group:"伙伴",value:0.08,effect:"战斗伙伴在场同行时，原生伤害增加{v}%",unit:"%",cap:undefined},
 protectCompanion: {name:"护伴",group:"伙伴",value:0.05,effect:"命中正在攻击小宝的敌人，为小宝提供{v}%最大生命护盾4秒，冷却6秒",unit:"%",cap:undefined},
 relayEdge: {name:"递锋",group:"伙伴",value:0.2,effect:"原生命中标记3秒，下一次真实伙伴命中增加{v}%并消耗",unit:"%",cap:undefined},
 returningBreath: {name:"归息",group:"伙伴",value:2,effect:"同行伙伴实际命中恢复玩家{v}点体力，冷却1秒",unit:"点",cap:undefined},
 sideBySide: {name:"并肩",group:"伙伴",value:0.15,effect:"同行伙伴命中标记3秒，下一次原生命中增加{v}%并消耗",unit:"%",cap:undefined},
 duet: {name:"双奏",group:"混合",value:0.2,effect:"两秒内同目标交替原生J和I，伤害增加{v}%",unit:"%",cap:undefined},
 storedTurn: {name:"蓄转",group:"混合",value:0.35,effect:"原生J终结命中后三秒内下一次原生I伤害增加{v}%",unit:"%",cap:undefined},
 guidingEdge: {name:"引刃",group:"混合",value:0.25,effect:"原生I标记3秒，下次第一段J伤害增加{v}%并消耗",unit:"%",cap:undefined},
 cyclicBreath: {name:"轮息",group:"混合",value:3,effect:"两秒内同目标原生J和I交替，恢复{v}点体力，冷却1秒",unit:"点",cap:undefined},
 duality: {name:"两仪",group:"混合",value:0.6,effect:"三秒内同目标完成J/I/J或I/J/I，产生{v}%基础伤害冲击，半径90、最多五目标、冷却3秒",unit:"%",cap:undefined},
} as const;
export const GIFT_RESONANCES = {
 oneLineArmy: {name:"一线破军",components:["gale", "pierceCurtain"],effect:"I贯穿至少两敌，末目标追加50%基础伤害"},
 unbrokenWind: {name:"风声不绝",components:["windRhythm", "echoWind"],effect:"回声命中后两秒内下一次I增伤25%"},
 quietSky: {name:"静风破云",components:["stillWind", "focusWind"],effect:"凝风或聚焦强化I命中标记3秒，下次原生追加40%基础伤害"},
 hundredCuts: {name:"百斩成锋",components:["blade", "chainedEdge", "catchEdge"],effect:"同一连段一二段均命中，终结追加40%基础伤害"},
 mountainEcho: {name:"山鸣破阵",components:["shock", "heavyEdge", "aftershock"],effect:"余震半径120，追加25%基础伤害"},
 breathCycle: {name:"息锋循环",components:["finalBreath", "breath"],effect:"终结返还体力后，两秒体力恢复额外增加15%"},
 riposteFormation: {name:"回锋成阵",components:["riposte", "breakStance"],effect:"精准弹反后的回锋剑气追加30%基础伤害"},
 borrowedBlade: {name:"借风还刃",components:["borrowWind", "clearMirror"],effect:"精准弹反强化I追加160毫秒后的40%基础伤害回声"},
 armoredVeil: {name:"风甲成幕",components:["armor", "firstVeil"],effect:"初幕被敌人击破后30%基础伤害冲击，冷却10秒"},
 springGrace: {name:"春泉余泽",components:["spring", "lingeringGrace"],effect:"遭遇结束的溢出治疗有50%转为40秒护盾"},
 dewSpring: {name:"滴露成泉",components:["drinkDew", "stopBleeding"],effect:"止血期间饮露治疗增加50%"},
 shadowChase: {name:"踏影追刃",components:["skimShadow", "stepEdge"],effect:"实际躲避后的强化J首次命中追加30%基础伤害剑气"},
 residualTide: {name:"残风成潮",components:["residualWind", "returningTide"],effect:"落地减速区域300毫秒后造成25%基础伤害"},
 windHunt: {name:"定风围猎",components:["holdWind", "curledWind", "delayedEdge"],effect:"成功牵引减速敌人后追加30%基础伤害"},
 relayTogether: {name:"递锋同行",components:["relayEdge", "sideBySide"],effect:"伙伴消耗递锋后，下一次原生追加30%基础伤害，持续3秒"},
 guardedReturn: {name:"护伴归息",components:["protectCompanion", "returningBreath"],effect:"小宝在护伴护盾期间实际命中，自身恢复1%最大生命，冷却2秒"},
 bladeDance: {name:"风刃轮舞",components:["duet", "storedTurn", "guidingEdge"],effect:"同目标三秒内终结/I/J，第三击追加50%基础伤害剑气，冷却3秒"},
 dualityFlow: {name:"两仪流转",components:["duality", "cyclicBreath"],effect:"两仪冲击实际命中，恢复3体力并获得3%生命护盾3秒"},
} as const;
export type ResonanceId=keyof typeof GIFT_RESONANCES;
